// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hub/v1/hub.proto

package hubv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CaptureDirective is a hub-initiated instruction sent to an agent.
type DirectiveAction int32

const (
	DirectiveAction_DIRECTIVE_ACTION_UNSPECIFIED DirectiveAction = 0
	DirectiveAction_DIRECTIVE_ACTION_START       DirectiveAction = 1
	DirectiveAction_DIRECTIVE_ACTION_STOP        DirectiveAction = 2
	DirectiveAction_DIRECTIVE_ACTION_UPDATE      DirectiveAction = 3
)

// Enum value maps for DirectiveAction.
var (
	DirectiveAction_name = map[int32]string{
		0: "DIRECTIVE_ACTION_UNSPECIFIED",
		1: "DIRECTIVE_ACTION_START",
		2: "DIRECTIVE_ACTION_STOP",
		3: "DIRECTIVE_ACTION_UPDATE",
	}
	DirectiveAction_value = map[string]int32{
		"DIRECTIVE_ACTION_UNSPECIFIED": 0,
		"DIRECTIVE_ACTION_START":       1,
		"DIRECTIVE_ACTION_STOP":        2,
		"DIRECTIVE_ACTION_UPDATE":      3,
	}
)

func (x DirectiveAction) Enum() *DirectiveAction {
	p := new(DirectiveAction)
	*p = x
	return p
}

func (x DirectiveAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DirectiveAction) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_hub_proto_enumTypes[0].Descriptor()
}

func (DirectiveAction) Type() protoreflect.EnumType {
	return &file_hub_v1_hub_proto_enumTypes[0]
}

func (x DirectiveAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DirectiveAction.Descriptor instead.
func (DirectiveAction) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{0}
}

type CapturePhase int32

const (
	CapturePhase_CAPTURE_PHASE_UNSPECIFIED CapturePhase = 0
	CapturePhase_CAPTURE_PHASE_PENDING     CapturePhase = 1
	CapturePhase_CAPTURE_PHASE_ACTIVE      CapturePhase = 2
	CapturePhase_CAPTURE_PHASE_COMPLETED   CapturePhase = 3
	CapturePhase_CAPTURE_PHASE_FAILED      CapturePhase = 4
)

// Enum value maps for CapturePhase.
var (
	CapturePhase_name = map[int32]string{
		0: "CAPTURE_PHASE_UNSPECIFIED",
		1: "CAPTURE_PHASE_PENDING",
		2: "CAPTURE_PHASE_ACTIVE",
		3: "CAPTURE_PHASE_COMPLETED",
		4: "CAPTURE_PHASE_FAILED",
	}
	CapturePhase_value = map[string]int32{
		"CAPTURE_PHASE_UNSPECIFIED": 0,
		"CAPTURE_PHASE_PENDING":     1,
		"CAPTURE_PHASE_ACTIVE":      2,
		"CAPTURE_PHASE_COMPLETED":   3,
		"CAPTURE_PHASE_FAILED":      4,
	}
)

func (x CapturePhase) Enum() *CapturePhase {
	p := new(CapturePhase)
	*p = x
	return p
}

func (x CapturePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapturePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_hub_proto_enumTypes[1].Descriptor()
}

func (CapturePhase) Type() protoreflect.EnumType {
	return &file_hub_v1_hub_proto_enumTypes[1]
}

func (x CapturePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapturePhase.Descriptor instead.
func (CapturePhase) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{1}
}

type AgentState int32

const (
	AgentState_AGENT_STATE_UNSPECIFIED  AgentState = 0
	AgentState_AGENT_STATE_CONNECTED    AgentState = 1
	AgentState_AGENT_STATE_DISCONNECTED AgentState = 2
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNSPECIFIED",
		1: "AGENT_STATE_CONNECTED",
		2: "AGENT_STATE_DISCONNECTED",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNSPECIFIED":  0,
		"AGENT_STATE_CONNECTED":    1,
		"AGENT_STATE_DISCONNECTED": 2,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_hub_v1_hub_proto_enumTypes[2].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_hub_v1_hub_proto_enumTypes[2]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{2}
}

type RegisterAgentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AgentId           string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClusterName       string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	KubernetesVersion string                 `protobuf:"bytes,3,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	// Capabilities advertised by the agent (e.g. supported storage backends).
	Capabilities  []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *RegisterAgentRequest) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *RegisterAgentRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type RegisterAgentResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Interval (seconds) at which the agent should send heartbeats.
	HeartbeatIntervalSeconds int32 `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAgentResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

type HeartbeatRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	AgentId          string                  `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ActiveCaptures   int32                   `protobuf:"varint,2,opt,name=active_captures,json=activeCaptures,proto3" json:"active_captures,omitempty"`
	CaptureSummaries []*CaptureStatusSummary `protobuf:"bytes,3,rep,name=capture_summaries,json=captureSummaries,proto3" json:"capture_summaries,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetActiveCaptures() int32 {
	if x != nil {
		return x.ActiveCaptures
	}
	return 0
}

func (x *HeartbeatRequest) GetCaptureSummaries() []*CaptureStatusSummary {
	if x != nil {
		return x.CaptureSummaries
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type DeregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentRequest) Reset() {
	*x = DeregisterAgentRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentRequest) ProtoMessage() {}

func (x *DeregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*DeregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{4}
}

func (x *DeregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DeregisterAgentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterAgentResponse) Reset() {
	*x = DeregisterAgentResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterAgentResponse) ProtoMessage() {}

func (x *DeregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*DeregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{5}
}

func (x *DeregisterAgentResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type WatchDirectivesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDirectivesRequest) Reset() {
	*x = WatchDirectivesRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDirectivesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDirectivesRequest) ProtoMessage() {}

func (x *WatchDirectivesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDirectivesRequest.ProtoReflect.Descriptor instead.
func (*WatchDirectivesRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{6}
}

func (x *WatchDirectivesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// WatchDirectivesResponse wraps a CaptureDirective for the streaming RPC.
type WatchDirectivesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Directive     *CaptureDirective      `protobuf:"bytes,1,opt,name=directive,proto3" json:"directive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchDirectivesResponse) Reset() {
	*x = WatchDirectivesResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchDirectivesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchDirectivesResponse) ProtoMessage() {}

func (x *WatchDirectivesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchDirectivesResponse.ProtoReflect.Descriptor instead.
func (*WatchDirectivesResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{7}
}

func (x *WatchDirectivesResponse) GetDirective() *CaptureDirective {
	if x != nil {
		return x.Directive
	}
	return nil
}

type CaptureDirective struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DirectiveId      string                 `protobuf:"bytes,1,opt,name=directive_id,json=directiveId,proto3" json:"directive_id,omitempty"`
	Action           DirectiveAction        `protobuf:"varint,2,opt,name=action,proto3,enum=hub.v1.DirectiveAction" json:"action,omitempty"`
	CaptureName      string                 `protobuf:"bytes,3,opt,name=capture_name,json=captureName,proto3" json:"capture_name,omitempty"`
	CaptureNamespace string                 `protobuf:"bytes,4,opt,name=capture_namespace,json=captureNamespace,proto3" json:"capture_namespace,omitempty"`
	// Serialised TrafficCapture spec for START / UPDATE directives.
	Spec          *CaptureSpec `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureDirective) Reset() {
	*x = CaptureDirective{}
	mi := &file_hub_v1_hub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureDirective) ProtoMessage() {}

func (x *CaptureDirective) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureDirective.ProtoReflect.Descriptor instead.
func (*CaptureDirective) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{8}
}

func (x *CaptureDirective) GetDirectiveId() string {
	if x != nil {
		return x.DirectiveId
	}
	return ""
}

func (x *CaptureDirective) GetAction() DirectiveAction {
	if x != nil {
		return x.Action
	}
	return DirectiveAction_DIRECTIVE_ACTION_UNSPECIFIED
}

func (x *CaptureDirective) GetCaptureName() string {
	if x != nil {
		return x.CaptureName
	}
	return ""
}

func (x *CaptureDirective) GetCaptureNamespace() string {
	if x != nil {
		return x.CaptureNamespace
	}
	return ""
}

func (x *CaptureDirective) GetSpec() *CaptureSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CaptureSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetRouteGroup string                 `protobuf:"bytes,1,opt,name=target_route_group,json=targetRouteGroup,proto3" json:"target_route_group,omitempty"`
	TargetRouteKind  string                 `protobuf:"bytes,2,opt,name=target_route_kind,json=targetRouteKind,proto3" json:"target_route_kind,omitempty"`
	TargetRouteName  string                 `protobuf:"bytes,3,opt,name=target_route_name,json=targetRouteName,proto3" json:"target_route_name,omitempty"`
	StorageRefName   string                 `protobuf:"bytes,4,opt,name=storage_ref_name,json=storageRefName,proto3" json:"storage_ref_name,omitempty"`
	CaptureSettings  *CaptureSettings       `protobuf:"bytes,5,opt,name=capture_settings,json=captureSettings,proto3" json:"capture_settings,omitempty"`
	Filters          *CaptureFilters        `protobuf:"bytes,6,opt,name=filters,proto3" json:"filters,omitempty"`
	AgentScaling     *AgentScaling          `protobuf:"bytes,7,opt,name=agent_scaling,json=agentScaling,proto3" json:"agent_scaling,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureSpec) Reset() {
	*x = CaptureSpec{}
	mi := &file_hub_v1_hub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSpec) ProtoMessage() {}

func (x *CaptureSpec) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSpec.ProtoReflect.Descriptor instead.
func (*CaptureSpec) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{9}
}

func (x *CaptureSpec) GetTargetRouteGroup() string {
	if x != nil {
		return x.TargetRouteGroup
	}
	return ""
}

func (x *CaptureSpec) GetTargetRouteKind() string {
	if x != nil {
		return x.TargetRouteKind
	}
	return ""
}

func (x *CaptureSpec) GetTargetRouteName() string {
	if x != nil {
		return x.TargetRouteName
	}
	return ""
}

func (x *CaptureSpec) GetStorageRefName() string {
	if x != nil {
		return x.StorageRefName
	}
	return ""
}

func (x *CaptureSpec) GetCaptureSettings() *CaptureSettings {
	if x != nil {
		return x.CaptureSettings
	}
	return nil
}

func (x *CaptureSpec) GetFilters() *CaptureFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *CaptureSpec) GetAgentScaling() *AgentScaling {
	if x != nil {
		return x.AgentScaling
	}
	return nil
}

type CaptureSettings struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeHeaders bool                   `protobuf:"varint,1,opt,name=include_headers,json=includeHeaders,proto3" json:"include_headers,omitempty"`
	IncludeBody    bool                   `protobuf:"varint,2,opt,name=include_body,json=includeBody,proto3" json:"include_body,omitempty"`
	MaxBodyBytes   int64                  `protobuf:"varint,3,opt,name=max_body_bytes,json=maxBodyBytes,proto3" json:"max_body_bytes,omitempty"`
	Duration       string                 `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptureSettings) Reset() {
	*x = CaptureSettings{}
	mi := &file_hub_v1_hub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureSettings) ProtoMessage() {}

func (x *CaptureSettings) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureSettings.ProtoReflect.Descriptor instead.
func (*CaptureSettings) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{10}
}

func (x *CaptureSettings) GetIncludeHeaders() bool {
	if x != nil {
		return x.IncludeHeaders
	}
	return false
}

func (x *CaptureSettings) GetIncludeBody() bool {
	if x != nil {
		return x.IncludeBody
	}
	return false
}

func (x *CaptureSettings) GetMaxBodyBytes() int64 {
	if x != nil {
		return x.MaxBodyBytes
	}
	return 0
}

func (x *CaptureSettings) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

type CaptureFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []*HeaderMatch         `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	PathPrefix    string                 `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Percentage    int32                  `protobuf:"varint,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CaptureFilters) Reset() {
	*x = CaptureFilters{}
	mi := &file_hub_v1_hub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureFilters) ProtoMessage() {}

func (x *CaptureFilters) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureFilters.ProtoReflect.Descriptor instead.
func (*CaptureFilters) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{11}
}

func (x *CaptureFilters) GetHeaders() []*HeaderMatch {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CaptureFilters) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *CaptureFilters) GetPercentage() int32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type HeaderMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderMatch) Reset() {
	*x = HeaderMatch{}
	mi := &file_hub_v1_hub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderMatch) ProtoMessage() {}

func (x *HeaderMatch) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderMatch.ProtoReflect.Descriptor instead.
func (*HeaderMatch) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{12}
}

func (x *HeaderMatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HeaderMatch) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AgentScaling struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      int32                  `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	MinReplicas   int32                  `protobuf:"varint,2,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	MaxReplicas   int32                  `protobuf:"varint,3,opt,name=max_replicas,json=maxReplicas,proto3" json:"max_replicas,omitempty"`
	TargetCpu     int32                  `protobuf:"varint,4,opt,name=target_cpu,json=targetCpu,proto3" json:"target_cpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentScaling) Reset() {
	*x = AgentScaling{}
	mi := &file_hub_v1_hub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentScaling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentScaling) ProtoMessage() {}

func (x *AgentScaling) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentScaling.ProtoReflect.Descriptor instead.
func (*AgentScaling) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{13}
}

func (x *AgentScaling) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AgentScaling) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *AgentScaling) GetMaxReplicas() int32 {
	if x != nil {
		return x.MaxReplicas
	}
	return 0
}

func (x *AgentScaling) GetTargetCpu() int32 {
	if x != nil {
		return x.TargetCpu
	}
	return 0
}

type CaptureStatusSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CaptureName      string                 `protobuf:"bytes,1,opt,name=capture_name,json=captureName,proto3" json:"capture_name,omitempty"`
	CaptureNamespace string                 `protobuf:"bytes,2,opt,name=capture_namespace,json=captureNamespace,proto3" json:"capture_namespace,omitempty"`
	Phase            CapturePhase           `protobuf:"varint,3,opt,name=phase,proto3,enum=hub.v1.CapturePhase" json:"phase,omitempty"`
	CapturedRequests int64                  `protobuf:"varint,4,opt,name=captured_requests,json=capturedRequests,proto3" json:"captured_requests,omitempty"`
	BytesWritten     int64                  `protobuf:"varint,5,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	ReadyReplicas    int32                  `protobuf:"varint,6,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas  int32                  `protobuf:"varint,7,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureStatusSummary) Reset() {
	*x = CaptureStatusSummary{}
	mi := &file_hub_v1_hub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStatusSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStatusSummary) ProtoMessage() {}

func (x *CaptureStatusSummary) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStatusSummary.ProtoReflect.Descriptor instead.
func (*CaptureStatusSummary) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{14}
}

func (x *CaptureStatusSummary) GetCaptureName() string {
	if x != nil {
		return x.CaptureName
	}
	return ""
}

func (x *CaptureStatusSummary) GetCaptureNamespace() string {
	if x != nil {
		return x.CaptureNamespace
	}
	return ""
}

func (x *CaptureStatusSummary) GetPhase() CapturePhase {
	if x != nil {
		return x.Phase
	}
	return CapturePhase_CAPTURE_PHASE_UNSPECIFIED
}

func (x *CaptureStatusSummary) GetCapturedRequests() int64 {
	if x != nil {
		return x.CapturedRequests
	}
	return 0
}

func (x *CaptureStatusSummary) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *CaptureStatusSummary) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *CaptureStatusSummary) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

type ReportCaptureStatusRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	AgentId       string                  `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Statuses      []*CaptureStatusSummary `protobuf:"bytes,2,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCaptureStatusRequest) Reset() {
	*x = ReportCaptureStatusRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCaptureStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCaptureStatusRequest) ProtoMessage() {}

func (x *ReportCaptureStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCaptureStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportCaptureStatusRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{15}
}

func (x *ReportCaptureStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportCaptureStatusRequest) GetStatuses() []*CaptureStatusSummary {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type ReportCaptureStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCaptureStatusResponse) Reset() {
	*x = ReportCaptureStatusResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCaptureStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCaptureStatusResponse) ProtoMessage() {}

func (x *ReportCaptureStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCaptureStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportCaptureStatusResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{16}
}

func (x *ReportCaptureStatusResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type ListCapturesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Optional: filter by namespace.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapturesRequest) Reset() {
	*x = ListCapturesRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapturesRequest) ProtoMessage() {}

func (x *ListCapturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapturesRequest.ProtoReflect.Descriptor instead.
func (*ListCapturesRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{17}
}

func (x *ListCapturesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ListCapturesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CaptureInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CaptureName      string                 `protobuf:"bytes,1,opt,name=capture_name,json=captureName,proto3" json:"capture_name,omitempty"`
	CaptureNamespace string                 `protobuf:"bytes,2,opt,name=capture_namespace,json=captureNamespace,proto3" json:"capture_namespace,omitempty"`
	AgentId          string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Phase            CapturePhase           `protobuf:"varint,4,opt,name=phase,proto3,enum=hub.v1.CapturePhase" json:"phase,omitempty"`
	CapturedRequests int64                  `protobuf:"varint,5,opt,name=captured_requests,json=capturedRequests,proto3" json:"captured_requests,omitempty"`
	BytesWritten     int64                  `protobuf:"varint,6,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	StartTime        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	ReadyReplicas    int32                  `protobuf:"varint,8,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas  int32                  `protobuf:"varint,9,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureInfo) Reset() {
	*x = CaptureInfo{}
	mi := &file_hub_v1_hub_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureInfo) ProtoMessage() {}

func (x *CaptureInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureInfo.ProtoReflect.Descriptor instead.
func (*CaptureInfo) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{18}
}

func (x *CaptureInfo) GetCaptureName() string {
	if x != nil {
		return x.CaptureName
	}
	return ""
}

func (x *CaptureInfo) GetCaptureNamespace() string {
	if x != nil {
		return x.CaptureNamespace
	}
	return ""
}

func (x *CaptureInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CaptureInfo) GetPhase() CapturePhase {
	if x != nil {
		return x.Phase
	}
	return CapturePhase_CAPTURE_PHASE_UNSPECIFIED
}

func (x *CaptureInfo) GetCapturedRequests() int64 {
	if x != nil {
		return x.CapturedRequests
	}
	return 0
}

func (x *CaptureInfo) GetBytesWritten() int64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

func (x *CaptureInfo) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CaptureInfo) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *CaptureInfo) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

type ListCapturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Captures      []*CaptureInfo         `protobuf:"bytes,1,rep,name=captures,proto3" json:"captures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapturesResponse) Reset() {
	*x = ListCapturesResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapturesResponse) ProtoMessage() {}

func (x *ListCapturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapturesResponse.ProtoReflect.Descriptor instead.
func (*ListCapturesResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{19}
}

func (x *ListCapturesResponse) GetCaptures() []*CaptureInfo {
	if x != nil {
		return x.Captures
	}
	return nil
}

type GetCaptureStatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CaptureName      string                 `protobuf:"bytes,1,opt,name=capture_name,json=captureName,proto3" json:"capture_name,omitempty"`
	CaptureNamespace string                 `protobuf:"bytes,2,opt,name=capture_namespace,json=captureNamespace,proto3" json:"capture_namespace,omitempty"`
	// If empty, returns aggregate across all agents.
	AgentId       string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptureStatusRequest) Reset() {
	*x = GetCaptureStatusRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptureStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptureStatusRequest) ProtoMessage() {}

func (x *GetCaptureStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptureStatusRequest.ProtoReflect.Descriptor instead.
func (*GetCaptureStatusRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{20}
}

func (x *GetCaptureStatusRequest) GetCaptureName() string {
	if x != nil {
		return x.CaptureName
	}
	return ""
}

func (x *GetCaptureStatusRequest) GetCaptureNamespace() string {
	if x != nil {
		return x.CaptureNamespace
	}
	return ""
}

func (x *GetCaptureStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetCaptureStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capture       *CaptureInfo           `protobuf:"bytes,1,opt,name=capture,proto3" json:"capture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCaptureStatusResponse) Reset() {
	*x = GetCaptureStatusResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCaptureStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCaptureStatusResponse) ProtoMessage() {}

func (x *GetCaptureStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCaptureStatusResponse.ProtoReflect.Descriptor instead.
func (*GetCaptureStatusResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{21}
}

func (x *GetCaptureStatusResponse) GetCapture() *CaptureInfo {
	if x != nil {
		return x.Capture
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_hub_v1_hub_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{22}
}

type AgentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AgentId        string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClusterName    string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	ActiveCaptures int32                  `protobuf:"varint,3,opt,name=active_captures,json=activeCaptures,proto3" json:"active_captures,omitempty"`
	LastHeartbeat  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	Capabilities   []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	State          AgentState             `protobuf:"varint,6,opt,name=state,proto3,enum=hub.v1.AgentState" json:"state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_hub_v1_hub_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{23}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *AgentInfo) GetActiveCaptures() int32 {
	if x != nil {
		return x.ActiveCaptures
	}
	return 0
}

func (x *AgentInfo) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *AgentInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentInfo) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNSPECIFIED
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_hub_v1_hub_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hub_v1_hub_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_hub_v1_hub_proto_rawDescGZIP(), []int{24}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

var File_hub_v1_hub_proto protoreflect.FileDescriptor

const file_hub_v1_hub_proto_rawDesc = "" +
	"\n" +
	"\x10hub/v1/hub.proto\x12\x06hub.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa7\x01\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12-\n" +
	"\x12kubernetes_version\x18\x03 \x01(\tR\x11kubernetesVersion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\x8b\x01\n" +
	"\x15RegisterAgentResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\"\xa1\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12'\n" +
	"\x0factive_captures\x18\x02 \x01(\x05R\x0eactiveCaptures\x12I\n" +
	"\x11capture_summaries\x18\x03 \x03(\v2\x1c.hub.v1.CaptureStatusSummaryR\x10captureSummaries\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"K\n" +
	"\x16DeregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"=\n" +
	"\x17DeregisterAgentResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"3\n" +
	"\x16WatchDirectivesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"Q\n" +
	"\x17WatchDirectivesResponse\x126\n" +
	"\tdirective\x18\x01 \x01(\v2\x18.hub.v1.CaptureDirectiveR\tdirective\"\xdf\x01\n" +
	"\x10CaptureDirective\x12!\n" +
	"\fdirective_id\x18\x01 \x01(\tR\vdirectiveId\x12/\n" +
	"\x06action\x18\x02 \x01(\x0e2\x17.hub.v1.DirectiveActionR\x06action\x12!\n" +
	"\fcapture_name\x18\x03 \x01(\tR\vcaptureName\x12+\n" +
	"\x11capture_namespace\x18\x04 \x01(\tR\x10captureNamespace\x12'\n" +
	"\x04spec\x18\x05 \x01(\v2\x13.hub.v1.CaptureSpecR\x04spec\"\xee\x02\n" +
	"\vCaptureSpec\x12,\n" +
	"\x12target_route_group\x18\x01 \x01(\tR\x10targetRouteGroup\x12*\n" +
	"\x11target_route_kind\x18\x02 \x01(\tR\x0ftargetRouteKind\x12*\n" +
	"\x11target_route_name\x18\x03 \x01(\tR\x0ftargetRouteName\x12(\n" +
	"\x10storage_ref_name\x18\x04 \x01(\tR\x0estorageRefName\x12B\n" +
	"\x10capture_settings\x18\x05 \x01(\v2\x17.hub.v1.CaptureSettingsR\x0fcaptureSettings\x120\n" +
	"\afilters\x18\x06 \x01(\v2\x16.hub.v1.CaptureFiltersR\afilters\x129\n" +
	"\ragent_scaling\x18\a \x01(\v2\x14.hub.v1.AgentScalingR\fagentScaling\"\x9f\x01\n" +
	"\x0fCaptureSettings\x12'\n" +
	"\x0finclude_headers\x18\x01 \x01(\bR\x0eincludeHeaders\x12!\n" +
	"\finclude_body\x18\x02 \x01(\bR\vincludeBody\x12$\n" +
	"\x0emax_body_bytes\x18\x03 \x01(\x03R\fmaxBodyBytes\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\tR\bduration\"\x80\x01\n" +
	"\x0eCaptureFilters\x12-\n" +
	"\aheaders\x18\x01 \x03(\v2\x13.hub.v1.HeaderMatchR\aheaders\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x05R\n" +
	"percentage\"7\n" +
	"\vHeaderMatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x8f\x01\n" +
	"\fAgentScaling\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12!\n" +
	"\fmin_replicas\x18\x02 \x01(\x05R\vminReplicas\x12!\n" +
	"\fmax_replicas\x18\x03 \x01(\x05R\vmaxReplicas\x12\x1d\n" +
	"\n" +
	"target_cpu\x18\x04 \x01(\x05R\ttargetCpu\"\xb6\x02\n" +
	"\x14CaptureStatusSummary\x12!\n" +
	"\fcapture_name\x18\x01 \x01(\tR\vcaptureName\x12+\n" +
	"\x11capture_namespace\x18\x02 \x01(\tR\x10captureNamespace\x12*\n" +
	"\x05phase\x18\x03 \x01(\x0e2\x14.hub.v1.CapturePhaseR\x05phase\x12+\n" +
	"\x11captured_requests\x18\x04 \x01(\x03R\x10capturedRequests\x12#\n" +
	"\rbytes_written\x18\x05 \x01(\x03R\fbytesWritten\x12%\n" +
	"\x0eready_replicas\x18\x06 \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10desired_replicas\x18\a \x01(\x05R\x0fdesiredReplicas\"q\n" +
	"\x1aReportCaptureStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x128\n" +
	"\bstatuses\x18\x02 \x03(\v2\x1c.hub.v1.CaptureStatusSummaryR\bstatuses\"A\n" +
	"\x1bReportCaptureStatusResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"N\n" +
	"\x13ListCapturesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x83\x03\n" +
	"\vCaptureInfo\x12!\n" +
	"\fcapture_name\x18\x01 \x01(\tR\vcaptureName\x12+\n" +
	"\x11capture_namespace\x18\x02 \x01(\tR\x10captureNamespace\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12*\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x14.hub.v1.CapturePhaseR\x05phase\x12+\n" +
	"\x11captured_requests\x18\x05 \x01(\x03R\x10capturedRequests\x12#\n" +
	"\rbytes_written\x18\x06 \x01(\x03R\fbytesWritten\x129\n" +
	"\n" +
	"start_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12%\n" +
	"\x0eready_replicas\x18\b \x01(\x05R\rreadyReplicas\x12)\n" +
	"\x10desired_replicas\x18\t \x01(\x05R\x0fdesiredReplicas\"G\n" +
	"\x14ListCapturesResponse\x12/\n" +
	"\bcaptures\x18\x01 \x03(\v2\x13.hub.v1.CaptureInfoR\bcaptures\"\x84\x01\n" +
	"\x17GetCaptureStatusRequest\x12!\n" +
	"\fcapture_name\x18\x01 \x01(\tR\vcaptureName\x12+\n" +
	"\x11capture_namespace\x18\x02 \x01(\tR\x10captureNamespace\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\"I\n" +
	"\x18GetCaptureStatusResponse\x12-\n" +
	"\acapture\x18\x01 \x01(\v2\x13.hub.v1.CaptureInfoR\acapture\"\x13\n" +
	"\x11ListAgentsRequest\"\x83\x02\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12'\n" +
	"\x0factive_captures\x18\x03 \x01(\x05R\x0eactiveCaptures\x12A\n" +
	"\x0elast_heartbeat\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12(\n" +
	"\x05state\x18\x06 \x01(\x0e2\x12.hub.v1.AgentStateR\x05state\"?\n" +
	"\x12ListAgentsResponse\x12)\n" +
	"\x06agents\x18\x01 \x03(\v2\x11.hub.v1.AgentInfoR\x06agents*\x87\x01\n" +
	"\x0fDirectiveAction\x12 \n" +
	"\x1cDIRECTIVE_ACTION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16DIRECTIVE_ACTION_START\x10\x01\x12\x19\n" +
	"\x15DIRECTIVE_ACTION_STOP\x10\x02\x12\x1b\n" +
	"\x17DIRECTIVE_ACTION_UPDATE\x10\x03*\x99\x01\n" +
	"\fCapturePhase\x12\x1d\n" +
	"\x19CAPTURE_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CAPTURE_PHASE_PENDING\x10\x01\x12\x18\n" +
	"\x14CAPTURE_PHASE_ACTIVE\x10\x02\x12\x1b\n" +
	"\x17CAPTURE_PHASE_COMPLETED\x10\x03\x12\x18\n" +
	"\x14CAPTURE_PHASE_FAILED\x10\x04*b\n" +
	"\n" +
	"AgentState\x12\x1b\n" +
	"\x17AGENT_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15AGENT_STATE_CONNECTED\x10\x01\x12\x1c\n" +
	"\x18AGENT_STATE_DISCONNECTED\x10\x022\x8d\x05\n" +
	"\n" +
	"HubService\x12L\n" +
	"\rRegisterAgent\x12\x1c.hub.v1.RegisterAgentRequest\x1a\x1d.hub.v1.RegisterAgentResponse\x12@\n" +
	"\tHeartbeat\x12\x18.hub.v1.HeartbeatRequest\x1a\x19.hub.v1.HeartbeatResponse\x12R\n" +
	"\x0fDeregisterAgent\x12\x1e.hub.v1.DeregisterAgentRequest\x1a\x1f.hub.v1.DeregisterAgentResponse\x12T\n" +
	"\x0fWatchDirectives\x12\x1e.hub.v1.WatchDirectivesRequest\x1a\x1f.hub.v1.WatchDirectivesResponse0\x01\x12^\n" +
	"\x13ReportCaptureStatus\x12\".hub.v1.ReportCaptureStatusRequest\x1a#.hub.v1.ReportCaptureStatusResponse\x12I\n" +
	"\fListCaptures\x12\x1b.hub.v1.ListCapturesRequest\x1a\x1c.hub.v1.ListCapturesResponse\x12U\n" +
	"\x10GetCaptureStatus\x12\x1f.hub.v1.GetCaptureStatusRequest\x1a .hub.v1.GetCaptureStatusResponse\x12C\n" +
	"\n" +
	"ListAgents\x12\x19.hub.v1.ListAgentsRequest\x1a\x1a.hub.v1.ListAgentsResponseB2Z0github.com/kapture-io/kapture/proto/hub/v1;hubv1b\x06proto3"

var (
	file_hub_v1_hub_proto_rawDescOnce sync.Once
	file_hub_v1_hub_proto_rawDescData []byte
)

func file_hub_v1_hub_proto_rawDescGZIP() []byte {
	file_hub_v1_hub_proto_rawDescOnce.Do(func() {
		file_hub_v1_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hub_v1_hub_proto_rawDesc), len(file_hub_v1_hub_proto_rawDesc)))
	})
	return file_hub_v1_hub_proto_rawDescData
}

var file_hub_v1_hub_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_hub_v1_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_hub_v1_hub_proto_goTypes = []any{
	(DirectiveAction)(0),                // 0: hub.v1.DirectiveAction
	(CapturePhase)(0),                   // 1: hub.v1.CapturePhase
	(AgentState)(0),                     // 2: hub.v1.AgentState
	(*RegisterAgentRequest)(nil),        // 3: hub.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),       // 4: hub.v1.RegisterAgentResponse
	(*HeartbeatRequest)(nil),            // 5: hub.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),           // 6: hub.v1.HeartbeatResponse
	(*DeregisterAgentRequest)(nil),      // 7: hub.v1.DeregisterAgentRequest
	(*DeregisterAgentResponse)(nil),     // 8: hub.v1.DeregisterAgentResponse
	(*WatchDirectivesRequest)(nil),      // 9: hub.v1.WatchDirectivesRequest
	(*WatchDirectivesResponse)(nil),     // 10: hub.v1.WatchDirectivesResponse
	(*CaptureDirective)(nil),            // 11: hub.v1.CaptureDirective
	(*CaptureSpec)(nil),                 // 12: hub.v1.CaptureSpec
	(*CaptureSettings)(nil),             // 13: hub.v1.CaptureSettings
	(*CaptureFilters)(nil),              // 14: hub.v1.CaptureFilters
	(*HeaderMatch)(nil),                 // 15: hub.v1.HeaderMatch
	(*AgentScaling)(nil),                // 16: hub.v1.AgentScaling
	(*CaptureStatusSummary)(nil),        // 17: hub.v1.CaptureStatusSummary
	(*ReportCaptureStatusRequest)(nil),  // 18: hub.v1.ReportCaptureStatusRequest
	(*ReportCaptureStatusResponse)(nil), // 19: hub.v1.ReportCaptureStatusResponse
	(*ListCapturesRequest)(nil),         // 20: hub.v1.ListCapturesRequest
	(*CaptureInfo)(nil),                 // 21: hub.v1.CaptureInfo
	(*ListCapturesResponse)(nil),        // 22: hub.v1.ListCapturesResponse
	(*GetCaptureStatusRequest)(nil),     // 23: hub.v1.GetCaptureStatusRequest
	(*GetCaptureStatusResponse)(nil),    // 24: hub.v1.GetCaptureStatusResponse
	(*ListAgentsRequest)(nil),           // 25: hub.v1.ListAgentsRequest
	(*AgentInfo)(nil),                   // 26: hub.v1.AgentInfo
	(*ListAgentsResponse)(nil),          // 27: hub.v1.ListAgentsResponse
	(*timestamppb.Timestamp)(nil),       // 28: google.protobuf.Timestamp
}
var file_hub_v1_hub_proto_depIdxs = []int32{
	17, // 0: hub.v1.HeartbeatRequest.capture_summaries:type_name -> hub.v1.CaptureStatusSummary
	11, // 1: hub.v1.WatchDirectivesResponse.directive:type_name -> hub.v1.CaptureDirective
	0,  // 2: hub.v1.CaptureDirective.action:type_name -> hub.v1.DirectiveAction
	12, // 3: hub.v1.CaptureDirective.spec:type_name -> hub.v1.CaptureSpec
	13, // 4: hub.v1.CaptureSpec.capture_settings:type_name -> hub.v1.CaptureSettings
	14, // 5: hub.v1.CaptureSpec.filters:type_name -> hub.v1.CaptureFilters
	16, // 6: hub.v1.CaptureSpec.agent_scaling:type_name -> hub.v1.AgentScaling
	15, // 7: hub.v1.CaptureFilters.headers:type_name -> hub.v1.HeaderMatch
	1,  // 8: hub.v1.CaptureStatusSummary.phase:type_name -> hub.v1.CapturePhase
	17, // 9: hub.v1.ReportCaptureStatusRequest.statuses:type_name -> hub.v1.CaptureStatusSummary
	1,  // 10: hub.v1.CaptureInfo.phase:type_name -> hub.v1.CapturePhase
	28, // 11: hub.v1.CaptureInfo.start_time:type_name -> google.protobuf.Timestamp
	21, // 12: hub.v1.ListCapturesResponse.captures:type_name -> hub.v1.CaptureInfo
	21, // 13: hub.v1.GetCaptureStatusResponse.capture:type_name -> hub.v1.CaptureInfo
	28, // 14: hub.v1.AgentInfo.last_heartbeat:type_name -> google.protobuf.Timestamp
	2,  // 15: hub.v1.AgentInfo.state:type_name -> hub.v1.AgentState
	26, // 16: hub.v1.ListAgentsResponse.agents:type_name -> hub.v1.AgentInfo
	3,  // 17: hub.v1.HubService.RegisterAgent:input_type -> hub.v1.RegisterAgentRequest
	5,  // 18: hub.v1.HubService.Heartbeat:input_type -> hub.v1.HeartbeatRequest
	7,  // 19: hub.v1.HubService.DeregisterAgent:input_type -> hub.v1.DeregisterAgentRequest
	9,  // 20: hub.v1.HubService.WatchDirectives:input_type -> hub.v1.WatchDirectivesRequest
	18, // 21: hub.v1.HubService.ReportCaptureStatus:input_type -> hub.v1.ReportCaptureStatusRequest
	20, // 22: hub.v1.HubService.ListCaptures:input_type -> hub.v1.ListCapturesRequest
	23, // 23: hub.v1.HubService.GetCaptureStatus:input_type -> hub.v1.GetCaptureStatusRequest
	25, // 24: hub.v1.HubService.ListAgents:input_type -> hub.v1.ListAgentsRequest
	4,  // 25: hub.v1.HubService.RegisterAgent:output_type -> hub.v1.RegisterAgentResponse
	6,  // 26: hub.v1.HubService.Heartbeat:output_type -> hub.v1.HeartbeatResponse
	8,  // 27: hub.v1.HubService.DeregisterAgent:output_type -> hub.v1.DeregisterAgentResponse
	10, // 28: hub.v1.HubService.WatchDirectives:output_type -> hub.v1.WatchDirectivesResponse
	19, // 29: hub.v1.HubService.ReportCaptureStatus:output_type -> hub.v1.ReportCaptureStatusResponse
	22, // 30: hub.v1.HubService.ListCaptures:output_type -> hub.v1.ListCapturesResponse
	24, // 31: hub.v1.HubService.GetCaptureStatus:output_type -> hub.v1.GetCaptureStatusResponse
	27, // 32: hub.v1.HubService.ListAgents:output_type -> hub.v1.ListAgentsResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_hub_v1_hub_proto_init() }
func file_hub_v1_hub_proto_init() {
	if File_hub_v1_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hub_v1_hub_proto_rawDesc), len(file_hub_v1_hub_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_v1_hub_proto_goTypes,
		DependencyIndexes: file_hub_v1_hub_proto_depIdxs,
		EnumInfos:         file_hub_v1_hub_proto_enumTypes,
		MessageInfos:      file_hub_v1_hub_proto_msgTypes,
	}.Build()
	File_hub_v1_hub_proto = out.File
	file_hub_v1_hub_proto_goTypes = nil
	file_hub_v1_hub_proto_depIdxs = nil
}
