// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: hub/v1/hub.proto

package hubv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HubService_RegisterSpoke_FullMethodName       = "/hub.v1.HubService/RegisterSpoke"
	HubService_Heartbeat_FullMethodName           = "/hub.v1.HubService/Heartbeat"
	HubService_DeregisterSpoke_FullMethodName     = "/hub.v1.HubService/DeregisterSpoke"
	HubService_WatchDirectives_FullMethodName     = "/hub.v1.HubService/WatchDirectives"
	HubService_ReportCaptureStatus_FullMethodName = "/hub.v1.HubService/ReportCaptureStatus"
	HubService_ReportReplayStatus_FullMethodName  = "/hub.v1.HubService/ReportReplayStatus"
	HubService_ListCaptures_FullMethodName        = "/hub.v1.HubService/ListCaptures"
	HubService_GetCaptureStatus_FullMethodName    = "/hub.v1.HubService/GetCaptureStatus"
	HubService_ListSpokes_FullMethodName          = "/hub.v1.HubService/ListSpokes"
	HubService_ListCells_FullMethodName           = "/hub.v1.HubService/ListCells"
	HubService_ListReplays_FullMethodName         = "/hub.v1.HubService/ListReplays"
)

// HubServiceClient is the client API for HubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HubService defines the gRPC API between the hub and spoke controllers.
type HubServiceClient interface {
	// Spoke lifecycle
	RegisterSpoke(ctx context.Context, in *RegisterSpokeRequest, opts ...grpc.CallOption) (*RegisterSpokeResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	DeregisterSpoke(ctx context.Context, in *DeregisterSpokeRequest, opts ...grpc.CallOption) (*DeregisterSpokeResponse, error)
	// Capture orchestration (hub → spoke directives via server-streaming)
	WatchDirectives(ctx context.Context, in *WatchDirectivesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchDirectivesResponse], error)
	// Status reporting (spoke → hub)
	ReportCaptureStatus(ctx context.Context, in *ReportCaptureStatusRequest, opts ...grpc.CallOption) (*ReportCaptureStatusResponse, error)
	ReportReplayStatus(ctx context.Context, in *ReportReplayStatusRequest, opts ...grpc.CallOption) (*ReportReplayStatusResponse, error)
	// Query API (for dashboards / CLI tooling)
	ListCaptures(ctx context.Context, in *ListCapturesRequest, opts ...grpc.CallOption) (*ListCapturesResponse, error)
	GetCaptureStatus(ctx context.Context, in *GetCaptureStatusRequest, opts ...grpc.CallOption) (*GetCaptureStatusResponse, error)
	ListSpokes(ctx context.Context, in *ListSpokesRequest, opts ...grpc.CallOption) (*ListSpokesResponse, error)
	ListCells(ctx context.Context, in *ListCellsRequest, opts ...grpc.CallOption) (*ListCellsResponse, error)
	ListReplays(ctx context.Context, in *ListReplaysRequest, opts ...grpc.CallOption) (*ListReplaysResponse, error)
}

type hubServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubServiceClient(cc grpc.ClientConnInterface) HubServiceClient {
	return &hubServiceClient{cc}
}

func (c *hubServiceClient) RegisterSpoke(ctx context.Context, in *RegisterSpokeRequest, opts ...grpc.CallOption) (*RegisterSpokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSpokeResponse)
	err := c.cc.Invoke(ctx, HubService_RegisterSpoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, HubService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) DeregisterSpoke(ctx context.Context, in *DeregisterSpokeRequest, opts ...grpc.CallOption) (*DeregisterSpokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeregisterSpokeResponse)
	err := c.cc.Invoke(ctx, HubService_DeregisterSpoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) WatchDirectives(ctx context.Context, in *WatchDirectivesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchDirectivesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HubService_ServiceDesc.Streams[0], HubService_WatchDirectives_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchDirectivesRequest, WatchDirectivesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchDirectivesClient = grpc.ServerStreamingClient[WatchDirectivesResponse]

func (c *hubServiceClient) ReportCaptureStatus(ctx context.Context, in *ReportCaptureStatusRequest, opts ...grpc.CallOption) (*ReportCaptureStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportCaptureStatusResponse)
	err := c.cc.Invoke(ctx, HubService_ReportCaptureStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ReportReplayStatus(ctx context.Context, in *ReportReplayStatusRequest, opts ...grpc.CallOption) (*ReportReplayStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportReplayStatusResponse)
	err := c.cc.Invoke(ctx, HubService_ReportReplayStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ListCaptures(ctx context.Context, in *ListCapturesRequest, opts ...grpc.CallOption) (*ListCapturesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCapturesResponse)
	err := c.cc.Invoke(ctx, HubService_ListCaptures_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) GetCaptureStatus(ctx context.Context, in *GetCaptureStatusRequest, opts ...grpc.CallOption) (*GetCaptureStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCaptureStatusResponse)
	err := c.cc.Invoke(ctx, HubService_GetCaptureStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ListSpokes(ctx context.Context, in *ListSpokesRequest, opts ...grpc.CallOption) (*ListSpokesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSpokesResponse)
	err := c.cc.Invoke(ctx, HubService_ListSpokes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ListCells(ctx context.Context, in *ListCellsRequest, opts ...grpc.CallOption) (*ListCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCellsResponse)
	err := c.cc.Invoke(ctx, HubService_ListCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubServiceClient) ListReplays(ctx context.Context, in *ListReplaysRequest, opts ...grpc.CallOption) (*ListReplaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReplaysResponse)
	err := c.cc.Invoke(ctx, HubService_ListReplays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubServiceServer is the server API for HubService service.
// All implementations must embed UnimplementedHubServiceServer
// for forward compatibility.
//
// HubService defines the gRPC API between the hub and spoke controllers.
type HubServiceServer interface {
	// Spoke lifecycle
	RegisterSpoke(context.Context, *RegisterSpokeRequest) (*RegisterSpokeResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	DeregisterSpoke(context.Context, *DeregisterSpokeRequest) (*DeregisterSpokeResponse, error)
	// Capture orchestration (hub → spoke directives via server-streaming)
	WatchDirectives(*WatchDirectivesRequest, grpc.ServerStreamingServer[WatchDirectivesResponse]) error
	// Status reporting (spoke → hub)
	ReportCaptureStatus(context.Context, *ReportCaptureStatusRequest) (*ReportCaptureStatusResponse, error)
	ReportReplayStatus(context.Context, *ReportReplayStatusRequest) (*ReportReplayStatusResponse, error)
	// Query API (for dashboards / CLI tooling)
	ListCaptures(context.Context, *ListCapturesRequest) (*ListCapturesResponse, error)
	GetCaptureStatus(context.Context, *GetCaptureStatusRequest) (*GetCaptureStatusResponse, error)
	ListSpokes(context.Context, *ListSpokesRequest) (*ListSpokesResponse, error)
	ListCells(context.Context, *ListCellsRequest) (*ListCellsResponse, error)
	ListReplays(context.Context, *ListReplaysRequest) (*ListReplaysResponse, error)
	mustEmbedUnimplementedHubServiceServer()
}

// UnimplementedHubServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubServiceServer struct{}

func (UnimplementedHubServiceServer) RegisterSpoke(context.Context, *RegisterSpokeRequest) (*RegisterSpokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSpoke not implemented")
}
func (UnimplementedHubServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedHubServiceServer) DeregisterSpoke(context.Context, *DeregisterSpokeRequest) (*DeregisterSpokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeregisterSpoke not implemented")
}
func (UnimplementedHubServiceServer) WatchDirectives(*WatchDirectivesRequest, grpc.ServerStreamingServer[WatchDirectivesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchDirectives not implemented")
}
func (UnimplementedHubServiceServer) ReportCaptureStatus(context.Context, *ReportCaptureStatusRequest) (*ReportCaptureStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportCaptureStatus not implemented")
}
func (UnimplementedHubServiceServer) ReportReplayStatus(context.Context, *ReportReplayStatusRequest) (*ReportReplayStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportReplayStatus not implemented")
}
func (UnimplementedHubServiceServer) ListCaptures(context.Context, *ListCapturesRequest) (*ListCapturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCaptures not implemented")
}
func (UnimplementedHubServiceServer) GetCaptureStatus(context.Context, *GetCaptureStatusRequest) (*GetCaptureStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCaptureStatus not implemented")
}
func (UnimplementedHubServiceServer) ListSpokes(context.Context, *ListSpokesRequest) (*ListSpokesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSpokes not implemented")
}
func (UnimplementedHubServiceServer) ListCells(context.Context, *ListCellsRequest) (*ListCellsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCells not implemented")
}
func (UnimplementedHubServiceServer) ListReplays(context.Context, *ListReplaysRequest) (*ListReplaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReplays not implemented")
}
func (UnimplementedHubServiceServer) mustEmbedUnimplementedHubServiceServer() {}
func (UnimplementedHubServiceServer) testEmbeddedByValue()                    {}

// UnsafeHubServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubServiceServer will
// result in compilation errors.
type UnsafeHubServiceServer interface {
	mustEmbedUnimplementedHubServiceServer()
}

func RegisterHubServiceServer(s grpc.ServiceRegistrar, srv HubServiceServer) {
	// If the following call pancis, it indicates UnimplementedHubServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubService_ServiceDesc, srv)
}

func _HubService_RegisterSpoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSpokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).RegisterSpoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_RegisterSpoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).RegisterSpoke(ctx, req.(*RegisterSpokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_DeregisterSpoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterSpokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).DeregisterSpoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_DeregisterSpoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).DeregisterSpoke(ctx, req.(*DeregisterSpokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_WatchDirectives_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDirectivesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HubServiceServer).WatchDirectives(m, &grpc.GenericServerStream[WatchDirectivesRequest, WatchDirectivesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HubService_WatchDirectivesServer = grpc.ServerStreamingServer[WatchDirectivesResponse]

func _HubService_ReportCaptureStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCaptureStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ReportCaptureStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ReportCaptureStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ReportCaptureStatus(ctx, req.(*ReportCaptureStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ReportReplayStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportReplayStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ReportReplayStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ReportReplayStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ReportReplayStatus(ctx, req.(*ReportReplayStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ListCaptures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCapturesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ListCaptures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ListCaptures_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ListCaptures(ctx, req.(*ListCapturesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_GetCaptureStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCaptureStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).GetCaptureStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_GetCaptureStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).GetCaptureStatus(ctx, req.(*GetCaptureStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ListSpokes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSpokesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ListSpokes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ListSpokes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ListSpokes(ctx, req.(*ListSpokesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ListCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ListCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ListCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ListCells(ctx, req.(*ListCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubService_ListReplays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReplaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubServiceServer).ListReplays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubService_ListReplays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubServiceServer).ListReplays(ctx, req.(*ListReplaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HubService_ServiceDesc is the grpc.ServiceDesc for HubService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hub.v1.HubService",
	HandlerType: (*HubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSpoke",
			Handler:    _HubService_RegisterSpoke_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _HubService_Heartbeat_Handler,
		},
		{
			MethodName: "DeregisterSpoke",
			Handler:    _HubService_DeregisterSpoke_Handler,
		},
		{
			MethodName: "ReportCaptureStatus",
			Handler:    _HubService_ReportCaptureStatus_Handler,
		},
		{
			MethodName: "ReportReplayStatus",
			Handler:    _HubService_ReportReplayStatus_Handler,
		},
		{
			MethodName: "ListCaptures",
			Handler:    _HubService_ListCaptures_Handler,
		},
		{
			MethodName: "GetCaptureStatus",
			Handler:    _HubService_GetCaptureStatus_Handler,
		},
		{
			MethodName: "ListSpokes",
			Handler:    _HubService_ListSpokes_Handler,
		},
		{
			MethodName: "ListCells",
			Handler:    _HubService_ListCells_Handler,
		},
		{
			MethodName: "ListReplays",
			Handler:    _HubService_ListReplays_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchDirectives",
			Handler:       _HubService_WatchDirectives_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hub/v1/hub.proto",
}
