// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: replayengine/v1/replayengine.proto

package replayenginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplayEngineService_Describe_FullMethodName  = "/replayengine.v1.ReplayEngineService/Describe"
	ReplayEngineService_Configure_FullMethodName = "/replayengine.v1.ReplayEngineService/Configure"
	ReplayEngineService_Execute_FullMethodName   = "/replayengine.v1.ReplayEngineService/Execute"
	ReplayEngineService_Drain_FullMethodName     = "/replayengine.v1.ReplayEngineService/Drain"
)

// ReplayEngineServiceClient is the client API for ReplayEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ReplayEngineService is the ABI between the Kapture replay host (the
// process that owns storage access, sharding, and pacing) and a replay
// engine (the process that actually sends load: the builtin sender, k6,
// ghz, or any third-party generator).
//
// The wire contract is deliberately narrow:
//
//   - The HOST owns data: it streams already-due, already-sharded requests
//     to the engine. Engines never see storage credentials, bucket
//     layouts, or shard math.
//   - The ENGINE owns sending: it turns FeedItems into real traffic and
//     reports results. Result granularity may be per-request
//     (RESULT events) or aggregate (SUMMARY metrics), depending on what
//     the underlying tool can observe.
//
// Engines are typically run as gRPC subprocesses discovered from a plugin
// directory; see docs/replay-engine-abi.md for the handshake, versioning,
// packaging, and hot-reload rules.
type ReplayEngineServiceClient interface {
	// Describe returns the engine identity and its supported ABI versions.
	// The host calls it first and refuses engines with no common version.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// Configure prepares the engine for a run. Called exactly once before
	// Execute. Engines must validate config here and fail fast.
	Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error)
	// Execute is the run itself: the host streams FeedItems (client stream)
	// and the engine streams ExecuteEvents back (server stream). The host
	// half-closes the feed when the capture slice is exhausted; the engine
	// finishes in-flight work, emits a final SUMMARY event, and closes its
	// side. Backpressure is gRPC flow control: engines that read slowly
	// slow the feed down, which is what keeps memory bounded on both sides.
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse], error)
	// Drain asks the engine to stop pulling new work and finish in-flight
	// requests. Used for hot reload and abort. Idempotent.
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
}

type replayEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplayEngineServiceClient(cc grpc.ClientConnInterface) ReplayEngineServiceClient {
	return &replayEngineServiceClient{cc}
}

func (c *replayEngineServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, ReplayEngineService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replayEngineServiceClient) Configure(ctx context.Context, in *ConfigureRequest, opts ...grpc.CallOption) (*ConfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureResponse)
	err := c.cc.Invoke(ctx, ReplayEngineService_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replayEngineServiceClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReplayEngineService_ServiceDesc.Streams[0], ReplayEngineService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplayEngineService_ExecuteClient = grpc.BidiStreamingClient[ExecuteRequest, ExecuteResponse]

func (c *replayEngineServiceClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, ReplayEngineService_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplayEngineServiceServer is the server API for ReplayEngineService service.
// All implementations must embed UnimplementedReplayEngineServiceServer
// for forward compatibility.
//
// ReplayEngineService is the ABI between the Kapture replay host (the
// process that owns storage access, sharding, and pacing) and a replay
// engine (the process that actually sends load: the builtin sender, k6,
// ghz, or any third-party generator).
//
// The wire contract is deliberately narrow:
//
//   - The HOST owns data: it streams already-due, already-sharded requests
//     to the engine. Engines never see storage credentials, bucket
//     layouts, or shard math.
//   - The ENGINE owns sending: it turns FeedItems into real traffic and
//     reports results. Result granularity may be per-request
//     (RESULT events) or aggregate (SUMMARY metrics), depending on what
//     the underlying tool can observe.
//
// Engines are typically run as gRPC subprocesses discovered from a plugin
// directory; see docs/replay-engine-abi.md for the handshake, versioning,
// packaging, and hot-reload rules.
type ReplayEngineServiceServer interface {
	// Describe returns the engine identity and its supported ABI versions.
	// The host calls it first and refuses engines with no common version.
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// Configure prepares the engine for a run. Called exactly once before
	// Execute. Engines must validate config here and fail fast.
	Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error)
	// Execute is the run itself: the host streams FeedItems (client stream)
	// and the engine streams ExecuteEvents back (server stream). The host
	// half-closes the feed when the capture slice is exhausted; the engine
	// finishes in-flight work, emits a final SUMMARY event, and closes its
	// side. Backpressure is gRPC flow control: engines that read slowly
	// slow the feed down, which is what keeps memory bounded on both sides.
	Execute(grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]) error
	// Drain asks the engine to stop pulling new work and finish in-flight
	// requests. Used for hot reload and abort. Idempotent.
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
	mustEmbedUnimplementedReplayEngineServiceServer()
}

// UnimplementedReplayEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplayEngineServiceServer struct{}

func (UnimplementedReplayEngineServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedReplayEngineServiceServer) Configure(context.Context, *ConfigureRequest) (*ConfigureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedReplayEngineServiceServer) Execute(grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedReplayEngineServiceServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedReplayEngineServiceServer) mustEmbedUnimplementedReplayEngineServiceServer() {}
func (UnimplementedReplayEngineServiceServer) testEmbeddedByValue()                             {}

// UnsafeReplayEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplayEngineServiceServer will
// result in compilation errors.
type UnsafeReplayEngineServiceServer interface {
	mustEmbedUnimplementedReplayEngineServiceServer()
}

func RegisterReplayEngineServiceServer(s grpc.ServiceRegistrar, srv ReplayEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedReplayEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplayEngineService_ServiceDesc, srv)
}

func _ReplayEngineService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayEngineServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplayEngineService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayEngineServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplayEngineService_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayEngineServiceServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplayEngineService_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayEngineServiceServer).Configure(ctx, req.(*ConfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplayEngineService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReplayEngineServiceServer).Execute(&grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReplayEngineService_ExecuteServer = grpc.BidiStreamingServer[ExecuteRequest, ExecuteResponse]

func _ReplayEngineService_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplayEngineServiceServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplayEngineService_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplayEngineServiceServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplayEngineService_ServiceDesc is the grpc.ServiceDesc for ReplayEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplayEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "replayengine.v1.ReplayEngineService",
	HandlerType: (*ReplayEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _ReplayEngineService_Describe_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _ReplayEngineService_Configure_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _ReplayEngineService_Drain_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _ReplayEngineService_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "replayengine/v1/replayengine.proto",
}
