FROM golang:1.25 AS builder

WORKDIR /src
COPY . .

ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/traffic-harvester-spoke ./cmd/spoke

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /out/traffic-harvester-spoke /traffic-harvester-spoke
ENTRYPOINT ["/traffic-harvester-spoke"]