FROM golang:1.26 AS builder

WORKDIR /src
COPY . .
RUN go mod download

ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/kapture-hub ./cmd/hub

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /out/kapture-hub /kapture-hub
ENTRYPOINT ["/kapture-hub"]