FROM golang:1.26 AS builder

WORKDIR /src
COPY . .
RUN go mod tidy

ARG TARGETOS=linux
ARG TARGETARCH=amd64
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/kapture-spoke ./cmd/spoke

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /out/kapture-spoke /kapture-spoke
ENTRYPOINT ["/kapture-spoke"]