/**
 * Kapture dashboard plugin SDK.
 *
 * A plugin contributes analytics panels to the /analytics dashboard.
 * Panels are ordinary React components that receive the capture's
 * streaming-statistics snapshot plus context, and render into a slot of
 * the panel grid. Plugins are registered at build time from
 * `src/plugins/index.ts` — drop a directory under `src/plugins/`,
 * export a `KapturePlugin`, add one `registerPlugin` line, and the
 * panels appear.
 *
 * See docs/ui-plugins.md for a walkthrough with a complete example.
 */

import type { ComponentType } from "react";
import type { StatsSnapshot } from "../stats-types";

/** Grid width hint for a panel. */
export type PanelWidth = "third" | "half" | "full";

/** Context passed to every panel alongside the data. */
export interface PanelContext {
  /** Capture the snapshot belongs to ("namespace/name"). */
  captureId: string;
  /** When the snapshot was generated by the agent. */
  generatedAt: string;
  /** True when the dashboard is showing mock data (no live agent). */
  mock: boolean;
}

/** Props every panel component receives. */
export interface PanelProps {
  snapshot: StatsSnapshot;
  context: PanelContext;
}

/** One dashboard panel contributed by a plugin. */
export interface PanelDefinition {
  /** Unique within the plugin (grid key is `pluginId:panelId`). */
  id: string;
  title: string;
  description?: string;
  /** Grid width hint; default "third". */
  width?: PanelWidth;
  /** Lower renders earlier; default 100. Built-ins use 10–40. */
  order?: number;
  component: ComponentType<PanelProps>;
}

/** A dashboard plugin: metadata plus the panels it contributes. */
export interface KapturePlugin {
  /** Unique plugin id (kebab-case). */
  id: string;
  name: string;
  version?: string;
  description?: string;
  panels: PanelDefinition[];
}
