import {
  TrafficCapture,
  CaptureStorage,
  Spoke,
  CapturedRequest,
} from "./types";

export const mockSpokes: Spoke[] = [
  {
    id: "spoke-us-east-1",
    clusterName: "prod-us-east-1",
    healthState: "Healthy",
    lastHeartbeat: new Date(Date.now() - 15000).toISOString(),
    activeCaptures: 3,
    version: "v0.4.0",
  },
  {
    id: "spoke-eu-west-1",
    clusterName: "prod-eu-west-1",
    healthState: "Healthy",
    lastHeartbeat: new Date(Date.now() - 22000).toISOString(),
    activeCaptures: 2,
    version: "v0.4.0",
  },
  {
    id: "spoke-ap-south-1",
    clusterName: "prod-ap-south-1",
    healthState: "Degraded",
    lastHeartbeat: new Date(Date.now() - 65000).toISOString(),
    activeCaptures: 1,
    version: "v0.3.2",
  },
  {
    id: "spoke-staging",
    clusterName: "staging-us-west-2",
    healthState: "Disconnected",
    lastHeartbeat: new Date(Date.now() - 300000).toISOString(),
    activeCaptures: 0,
    version: "v0.3.2",
  },
];

export const mockStorages: CaptureStorage[] = [
  {
    name: "prod-s3-store",
    namespace: "kapture-system",
    type: "S3",
    phase: "Ready",
    bucket: "kapture-captures-prod",
    region: "us-east-1",
    prefix: "captures/",
    retention: { maxAge: "30d", maxSize: "500Gi" },
  },
  {
    name: "eu-gcs-store",
    namespace: "kapture-system",
    type: "GCS",
    phase: "Ready",
    bucket: "kapture-captures-eu",
    region: "europe-west1",
    prefix: "eu-captures/",
    retention: { maxAge: "14d" },
  },
  {
    name: "staging-efs",
    namespace: "kapture-staging",
    type: "EFS",
    phase: "Ready",
    retention: { maxAge: "7d", maxSize: "100Gi" },
  },
  {
    name: "dev-s3-store",
    namespace: "kapture-dev",
    type: "S3",
    phase: "Error",
    bucket: "kapture-dev-bucket",
    region: "us-west-2",
  },
];

export const mockCaptures: TrafficCapture[] = [
  {
    name: "api-gateway-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "api-gateway-route",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: true, maxBodyBytes: 65536 },
      filters: { pathPrefix: "/api/v1", percentage: 50 },
      agent: {
        replicas: 3,
        minReplicas: 2,
        maxReplicas: 10,
        targetCPU: 70,
      },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 3600000 * 4).toISOString(),
      capturedRequests: 284712,
      bytesWritten: "1.2Gi",
      agentStatus: { readyReplicas: 3, desiredReplicas: 3 },
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "checkout-flow-debug",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "checkout-route",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: {
        includeHeaders: true,
        includeBody: true,
        maxBodyBytes: 131072,
        duration: "2h",
      },
      filters: {
        pathPrefix: "/checkout",
        headers: [{ name: "x-debug", value: "true" }],
      },
      agent: { replicas: 2, minReplicas: 1, maxReplicas: 5, targetCPU: 80 },
    },
    status: {
      phase: "Completed",
      startTime: new Date(Date.now() - 3600000 * 24).toISOString(),
      capturedRequests: 15234,
      bytesWritten: "89.4Mi",
      agentStatus: { readyReplicas: 0, desiredReplicas: 0 },
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "eu-payments-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "payments-route",
      },
      storageRef: { name: "eu-gcs-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: false },
      filters: { percentage: 25 },
      agent: { replicas: 2, minReplicas: 1, maxReplicas: 8, targetCPU: 75 },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 3600000 * 2).toISOString(),
      capturedRequests: 92341,
      bytesWritten: "312.7Mi",
      agentStatus: { readyReplicas: 2, desiredReplicas: 2 },
      spokeId: "spoke-eu-west-1",
    },
  },
  {
    name: "grpc-service-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "GRPCRoute",
        name: "user-service-grpc",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: true, maxBodyBytes: 32768 },
      agent: { replicas: 1, minReplicas: 1, maxReplicas: 4, targetCPU: 65 },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 3600000).toISOString(),
      capturedRequests: 18943,
      bytesWritten: "45.2Mi",
      agentStatus: { readyReplicas: 1, desiredReplicas: 1 },
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "ap-traffic-sample",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "main-ingress",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: false, includeBody: false },
      filters: { percentage: 10 },
      agent: { replicas: 1, minReplicas: 1, maxReplicas: 3, targetCPU: 80 },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 7200000).toISOString(),
      capturedRequests: 5621,
      bytesWritten: "8.1Mi",
      agentStatus: { readyReplicas: 1, desiredReplicas: 1 },
      spokeId: "spoke-ap-south-1",
    },
  },
  {
    name: "failed-capture-test",
    namespace: "kapture-dev",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "test-route",
      },
      storageRef: { name: "dev-s3-store", namespace: "kapture-dev" },
      capture: { includeHeaders: true, includeBody: true },
      agent: { replicas: 1 },
    },
    status: {
      phase: "Failed",
      capturedRequests: 0,
      bytesWritten: "0",
      spokeId: "spoke-staging",
    },
  },
  {
    name: "pending-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 300000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "new-service-route",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: false },
      agent: { replicas: 2, minReplicas: 1, maxReplicas: 6 },
    },
    status: {
      phase: "Pending",
      capturedRequests: 0,
      bytesWritten: "0",
      spokeId: "spoke-us-east-1",
    },
  },
];

export const mockCapturedRequests: CapturedRequest[] = [
  {
    id: "req-a1b2c3d4",
    timestamp: new Date(Date.now() - 5000).toISOString(),
    method: "POST",
    path: "/api/v1/orders",
    headers: {
      "content-type": ["application/json"],
      "x-request-id": ["abc-123-def"],
      authorization: ["Bearer ***"],
    },
    contentLength: 1234,
    protocol: "HTTP",
    statusHint: 201,
    metadata: { host: "api.example.com", remoteAddr: "10.0.1.45:52341" },
  },
  {
    id: "req-e5f6g7h8",
    timestamp: new Date(Date.now() - 8000).toISOString(),
    method: "GET",
    path: "/api/v1/products?category=electronics&page=2",
    headers: {
      accept: ["application/json"],
      "x-request-id": ["xyz-456-uvw"],
    },
    contentLength: 0,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.2.12:48921" },
  },
  {
    id: "req-i9j0k1l2",
    timestamp: new Date(Date.now() - 12000).toISOString(),
    method: "PUT",
    path: "/api/v1/users/usr_8391/preferences",
    headers: {
      "content-type": ["application/json"],
      "x-request-id": ["mno-789-pqr"],
    },
    contentLength: 567,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.1.88:39102" },
  },
  {
    id: "req-m3n4o5p6",
    timestamp: new Date(Date.now() - 15000).toISOString(),
    method: "DELETE",
    path: "/api/v1/cart/items/item_2847",
    headers: {
      "x-request-id": ["stu-012-vwx"],
      authorization: ["Bearer ***"],
    },
    contentLength: 0,
    protocol: "HTTP",
    statusHint: 204,
    metadata: { host: "api.example.com", remoteAddr: "10.0.3.22:41567" },
  },
  {
    id: "req-q7r8s9t0",
    timestamp: new Date(Date.now() - 20000).toISOString(),
    method: "POST",
    path: "/api/v1/auth/refresh",
    headers: {
      "content-type": ["application/json"],
      "x-request-id": ["yza-345-bcd"],
    },
    contentLength: 89,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.1.45:52342" },
  },
  {
    id: "req-u1v2w3x4",
    timestamp: new Date(Date.now() - 25000).toISOString(),
    method: "GET",
    path: "/api/v1/orders/ord_9182/status",
    headers: {
      accept: ["application/json"],
      "x-request-id": ["efg-678-hij"],
    },
    contentLength: 0,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.2.33:50182" },
  },
];
