import {
  TrafficCapture,
  CaptureStorage,
  Spoke,
  CapturedRequest,
  CaptureLoadTest,
  TrafficReplay,
  Cell,
} from "./types";
import { StatsSnapshot, WindowCounts } from "./stats-types";

export const mockSpokes: Spoke[] = [
  {
    id: "spoke-us-east-1",
    clusterName: "prod-us-east-1",
    healthState: "Healthy",
    lastHeartbeat: new Date(Date.now() - 15000).toISOString(),
    activeCaptures: 3,
    activeReplays: 2,
    cell: "cell-us-east",
    version: "v0.4.0",
  },
  {
    id: "spoke-eu-west-1",
    clusterName: "prod-eu-west-1",
    healthState: "Healthy",
    lastHeartbeat: new Date(Date.now() - 22000).toISOString(),
    activeCaptures: 2,
    activeReplays: 2,
    cell: "cell-eu-west",
    version: "v0.4.0",
  },
  {
    id: "spoke-ap-south-1",
    clusterName: "prod-ap-south-1",
    healthState: "Degraded",
    lastHeartbeat: new Date(Date.now() - 65000).toISOString(),
    activeCaptures: 1,
    activeReplays: 0,
    cell: "cell-ap-south",
    version: "v0.3.2",
  },
  {
    id: "spoke-staging",
    clusterName: "staging-us-west-2",
    healthState: "Disconnected",
    lastHeartbeat: new Date(Date.now() - 300000).toISOString(),
    activeCaptures: 0,
    activeReplays: 0,
    cell: "cell-staging",
    version: "v0.3.2",
  },
];

export const mockStorages: CaptureStorage[] = [
  {
    name: "prod-s3-store",
    namespace: "kapture-system",
    type: "S3",
    phase: "Ready",
    bucket: "kapture-captures-prod",
    region: "us-east-1",
    prefix: "captures/",
    retention: { maxAge: "30d", maxSize: "500Gi" },
  },
  {
    name: "eu-gcs-store",
    namespace: "kapture-system",
    type: "GCS",
    phase: "Ready",
    bucket: "kapture-captures-eu",
    region: "europe-west1",
    prefix: "eu-captures/",
    retention: { maxAge: "14d" },
  },
  {
    name: "staging-efs",
    namespace: "kapture-staging",
    type: "EFS",
    phase: "Ready",
    retention: { maxAge: "7d", maxSize: "100Gi" },
  },
  {
    name: "dev-s3-store",
    namespace: "kapture-dev",
    type: "S3",
    phase: "Error",
    bucket: "kapture-dev-bucket",
    region: "us-west-2",
  },
];

export const mockCaptures: TrafficCapture[] = [
  {
    name: "api-gateway-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "api-gateway-route",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: true, maxBodyBytes: 65536 },
      filters: { pathPrefix: "/api/v1", percentage: 50 },
      agent: {
        replicas: 3,
        minReplicas: 2,
        maxReplicas: 10,
        targetCPU: 70,
      },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 3600000 * 4).toISOString(),
      capturedRequests: 284712,
      bytesWritten: "1.2Gi",
      agentStatus: { readyReplicas: 3, desiredReplicas: 3 },
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "checkout-flow-debug",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "checkout-route",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: {
        includeHeaders: true,
        includeBody: true,
        maxBodyBytes: 131072,
        duration: "2h",
      },
      filters: {
        pathPrefix: "/checkout",
        headers: [{ name: "x-debug", value: "true" }],
      },
      agent: { replicas: 2, minReplicas: 1, maxReplicas: 5, targetCPU: 80 },
    },
    status: {
      phase: "Completed",
      startTime: new Date(Date.now() - 3600000 * 24).toISOString(),
      capturedRequests: 15234,
      bytesWritten: "89.4Mi",
      agentStatus: { readyReplicas: 0, desiredReplicas: 0 },
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "eu-payments-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "payments-route",
      },
      storageRef: { name: "eu-gcs-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: false },
      filters: { percentage: 25 },
      agent: { replicas: 2, minReplicas: 1, maxReplicas: 8, targetCPU: 75 },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 3600000 * 2).toISOString(),
      capturedRequests: 92341,
      bytesWritten: "312.7Mi",
      agentStatus: { readyReplicas: 2, desiredReplicas: 2 },
      spokeId: "spoke-eu-west-1",
    },
  },
  {
    name: "grpc-service-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "GRPCRoute",
        name: "user-service-grpc",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: true, maxBodyBytes: 32768 },
      agent: { replicas: 1, minReplicas: 1, maxReplicas: 4, targetCPU: 65 },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 3600000).toISOString(),
      capturedRequests: 18943,
      bytesWritten: "45.2Mi",
      agentStatus: { readyReplicas: 1, desiredReplicas: 1 },
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "ap-traffic-sample",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "main-ingress",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: false, includeBody: false },
      filters: { percentage: 10 },
      agent: { replicas: 1, minReplicas: 1, maxReplicas: 3, targetCPU: 80 },
    },
    status: {
      phase: "Active",
      startTime: new Date(Date.now() - 7200000).toISOString(),
      capturedRequests: 5621,
      bytesWritten: "8.1Mi",
      agentStatus: { readyReplicas: 1, desiredReplicas: 1 },
      spokeId: "spoke-ap-south-1",
    },
  },
  {
    name: "failed-capture-test",
    namespace: "kapture-dev",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "test-route",
      },
      storageRef: { name: "dev-s3-store", namespace: "kapture-dev" },
      capture: { includeHeaders: true, includeBody: true },
      agent: { replicas: 1 },
    },
    status: {
      phase: "Failed",
      capturedRequests: 0,
      bytesWritten: "0",
      spokeId: "spoke-staging",
    },
  },
  {
    name: "pending-capture",
    namespace: "kapture-system",
    createdAt: new Date(Date.now() - 300000).toISOString(),
    spec: {
      targetRef: {
        group: "gateway.networking.k8s.io",
        kind: "HTTPRoute",
        name: "new-service-route",
      },
      storageRef: { name: "prod-s3-store", namespace: "kapture-system" },
      capture: { includeHeaders: true, includeBody: false },
      agent: { replicas: 2, minReplicas: 1, maxReplicas: 6 },
    },
    status: {
      phase: "Pending",
      capturedRequests: 0,
      bytesWritten: "0",
      spokeId: "spoke-us-east-1",
    },
  },
];

export const mockCapturedRequests: CapturedRequest[] = [
  {
    id: "req-a1b2c3d4",
    timestamp: new Date(Date.now() - 5000).toISOString(),
    method: "POST",
    path: "/api/v1/orders",
    headers: {
      "content-type": ["application/json"],
      "x-request-id": ["abc-123-def"],
      authorization: ["Bearer ***"],
    },
    contentLength: 1234,
    protocol: "HTTP",
    statusHint: 201,
    metadata: { host: "api.example.com", remoteAddr: "10.0.1.45:52341" },
  },
  {
    id: "req-e5f6g7h8",
    timestamp: new Date(Date.now() - 8000).toISOString(),
    method: "GET",
    path: "/api/v1/products?category=electronics&page=2",
    headers: {
      accept: ["application/json"],
      "x-request-id": ["xyz-456-uvw"],
    },
    contentLength: 0,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.2.12:48921" },
  },
  {
    id: "req-i9j0k1l2",
    timestamp: new Date(Date.now() - 12000).toISOString(),
    method: "PUT",
    path: "/api/v1/users/usr_8391/preferences",
    headers: {
      "content-type": ["application/json"],
      "x-request-id": ["mno-789-pqr"],
    },
    contentLength: 567,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.1.88:39102" },
  },
  {
    id: "req-m3n4o5p6",
    timestamp: new Date(Date.now() - 15000).toISOString(),
    method: "DELETE",
    path: "/api/v1/cart/items/item_2847",
    headers: {
      "x-request-id": ["stu-012-vwx"],
      authorization: ["Bearer ***"],
    },
    contentLength: 0,
    protocol: "HTTP",
    statusHint: 204,
    metadata: { host: "api.example.com", remoteAddr: "10.0.3.22:41567" },
  },
  {
    id: "req-q7r8s9t0",
    timestamp: new Date(Date.now() - 20000).toISOString(),
    method: "POST",
    path: "/api/v1/auth/refresh",
    headers: {
      "content-type": ["application/json"],
      "x-request-id": ["yza-345-bcd"],
    },
    contentLength: 89,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.1.45:52342" },
  },
  {
    id: "req-u1v2w3x4",
    timestamp: new Date(Date.now() - 25000).toISOString(),
    method: "GET",
    path: "/api/v1/orders/ord_9182/status",
    headers: {
      accept: ["application/json"],
      "x-request-id": ["efg-678-hij"],
    },
    contentLength: 0,
    protocol: "HTTP",
    statusHint: 200,
    metadata: { host: "api.example.com", remoteAddr: "10.0.2.33:50182" },
  },
];

export const mockCells: Cell[] = [
  {
    name: "cell-us-east",
    connectedSpokes: 1,
    totalSpokes: 1,
    activeCaptures: 3,
    activeReplays: 2,
  },
  {
    name: "cell-eu-west",
    connectedSpokes: 1,
    totalSpokes: 1,
    activeCaptures: 2,
    activeReplays: 2,
  },
  {
    name: "cell-ap-south",
    connectedSpokes: 1,
    totalSpokes: 1,
    activeCaptures: 1,
    activeReplays: 0,
  },
  {
    name: "cell-staging",
    connectedSpokes: 0,
    totalSpokes: 1,
    activeCaptures: 0,
    activeReplays: 0,
  },
];

export const mockLoadTests: CaptureLoadTest[] = [
  {
    name: "orders-peak-replay",
    namespace: "default",
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    spec: {
      sourceRef: { name: "orders-api-capture" },
      storageRef: { name: "prod-s3-storage" },
      target: { host: "orders.staging.internal", port: 8080 },
      rate: { mode: "Constant", requestsPerSecond: 2000 },
      distribution: {
        cells: ["cell-us-east", "cell-eu-west"],
        workersPerSpoke: 2,
        concurrencyPerWorker: 25,
        presharded: true,
      },
      engine: { name: "k6" },
    },
    status: {
      phase: "Running",
      startTime: new Date(Date.now() - 1500000).toISOString(),
      totalShards: 4,
      assignedSpokes: 2,
      completedShards: 1,
      failedShards: 0,
      totalRequests: 400000,
      sentRequests: 261500,
      failedRequests: 342,
      achievedRPS: "1962.4",
      assignments: [
        { spokeID: "spoke-us-east-1", cell: "cell-us-east", shardIndexes: [0, 1] },
        { spokeID: "spoke-eu-west-1", cell: "cell-eu-west", shardIndexes: [2, 3] },
      ],
      cells: [
        {
          name: "cell-us-east",
          spokes: 1,
          shards: 2,
          sentRequests: 131200,
          failedRequests: 121,
        },
        {
          name: "cell-eu-west",
          spokes: 1,
          shards: 2,
          sentRequests: 130300,
          failedRequests: 221,
        },
      ],
    },
  },
  {
    name: "checkout-soak",
    namespace: "default",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    spec: {
      sourceRef: { name: "checkout-capture" },
      storageRef: { name: "prod-s3-storage" },
      target: { host: "checkout.staging.internal", tls: true },
      rate: { mode: "OriginalTiming" },
      distribution: { cells: ["cell-us-east"], workersPerSpoke: 1 },
      engine: { name: "builtin" },
    },
    status: {
      phase: "Completed",
      startTime: new Date(Date.now() - 86000000).toISOString(),
      completionTime: new Date(Date.now() - 82400000).toISOString(),
      totalShards: 1,
      assignedSpokes: 1,
      completedShards: 1,
      failedShards: 0,
      totalRequests: 52000,
      sentRequests: 51987,
      failedRequests: 13,
      achievedRPS: "14.4",
      assignments: [
        { spokeID: "spoke-us-east-1", cell: "cell-us-east", shardIndexes: [0] },
      ],
    },
  },
  {
    name: "payments-spike",
    namespace: "payments",
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    spec: {
      sourceRef: { name: "payments-capture" },
      storageRef: { name: "payments-gcs" },
      target: { host: "payments.staging.internal" },
      rate: { mode: "Constant", requestsPerSecond: 5000 },
      distribution: { workersPerSpoke: 4 },
      engine: { name: "ghz" },
    },
    status: {
      phase: "Aborted",
      startTime: new Date(Date.now() - 7000000).toISOString(),
      completionTime: new Date(Date.now() - 6800000).toISOString(),
      totalShards: 8,
      assignedSpokes: 2,
      completedShards: 0,
      failedShards: 3,
      totalRequests: 800000,
      sentRequests: 92100,
      failedRequests: 11812,
      achievedRPS: "4310.0",
    },
  },
];

export const mockReplays: TrafficReplay[] = [
  {
    name: "orders-peak-replay-shard-0",
    namespace: "default",
    createdAt: new Date(Date.now() - 1500000).toISOString(),
    spec: {
      sourceRef: { name: "orders-api-capture" },
      target: { host: "orders.staging.internal", port: 8080 },
      shard: { index: 0, count: 4, presharded: true },
      loadTestRef: { name: "orders-peak-replay" },
      engine: { name: "k6" },
    },
    status: {
      phase: "Completed",
      startTime: new Date(Date.now() - 1500000).toISOString(),
      completionTime: new Date(Date.now() - 300000).toISOString(),
      totalRequests: 100000,
      sentRequests: 99958,
      failedRequests: 42,
      p50Latency: "12ms",
      p95Latency: "48ms",
      p99Latency: "103ms",
      achievedRPS: "490.6",
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "orders-peak-replay-shard-1",
    namespace: "default",
    createdAt: new Date(Date.now() - 1500000).toISOString(),
    spec: {
      sourceRef: { name: "orders-api-capture" },
      target: { host: "orders.staging.internal", port: 8080 },
      shard: { index: 1, count: 4, presharded: true },
      loadTestRef: { name: "orders-peak-replay" },
      engine: { name: "k6" },
    },
    status: {
      phase: "Running",
      startTime: new Date(Date.now() - 1500000).toISOString(),
      totalRequests: 100000,
      sentRequests: 61542,
      failedRequests: 79,
      achievedRPS: "492.1",
      spokeId: "spoke-us-east-1",
    },
  },
  {
    name: "orders-peak-replay-shard-2",
    namespace: "default",
    createdAt: new Date(Date.now() - 1500000).toISOString(),
    spec: {
      sourceRef: { name: "orders-api-capture" },
      target: { host: "orders.staging.internal", port: 8080 },
      shard: { index: 2, count: 4, presharded: true },
      loadTestRef: { name: "orders-peak-replay" },
      engine: { name: "k6" },
    },
    status: {
      phase: "Running",
      startTime: new Date(Date.now() - 1450000).toISOString(),
      totalRequests: 100000,
      sentRequests: 58230,
      failedRequests: 101,
      achievedRPS: "488.9",
      spokeId: "spoke-eu-west-1",
    },
  },
  {
    name: "orders-peak-replay-shard-3",
    namespace: "default",
    createdAt: new Date(Date.now() - 1500000).toISOString(),
    spec: {
      sourceRef: { name: "orders-api-capture" },
      target: { host: "orders.staging.internal", port: 8080 },
      shard: { index: 3, count: 4, presharded: true },
      loadTestRef: { name: "orders-peak-replay" },
      engine: { name: "k6" },
    },
    status: {
      phase: "Running",
      startTime: new Date(Date.now() - 1450000).toISOString(),
      totalRequests: 100000,
      sentRequests: 41770,
      failedRequests: 120,
      achievedRPS: "489.3",
      spokeId: "spoke-eu-west-1",
    },
  },
  {
    name: "manual-orders-replay",
    namespace: "default",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    spec: {
      sourceRef: { name: "orders-api-capture" },
      target: { host: "dev.orders.internal" },
      engine: { name: "builtin" },
    },
    status: {
      phase: "Completed",
      startTime: new Date(Date.now() - 3600000).toISOString(),
      completionTime: new Date(Date.now() - 3000000).toISOString(),
      totalRequests: 5000,
      sentRequests: 5000,
      failedRequests: 0,
      p50Latency: "9ms",
      p95Latency: "31ms",
      p99Latency: "77ms",
      achievedRPS: "8.3",
      spokeId: "spoke-us-east-1",
    },
  },
];

function mockWindow(minutesAgo: number, requests: number): WindowCounts {
  const start = new Date(Date.now() - minutesAgo * 60000);
  start.setSeconds(0, 0);
  const get = Math.round(requests * 0.62);
  const post = Math.round(requests * 0.27);
  const put = Math.round(requests * 0.06);
  const del = Math.round(requests * 0.03);
  return {
    start: start.toISOString(),
    end: new Date(start.getTime() + 60000).toISOString(),
    requests,
    bytes: requests * 840,
    meanBytes: 840,
    byMethod: {
      GET: get,
      POST: post,
      PUT: put,
      DELETE: del,
      PATCH: requests - get - post - put - del,
    },
    byProtocol: { HTTP: Math.round(requests * 0.9), gRPC: Math.round(requests * 0.1) },
    newFlows: Math.max(2, Math.round(requests * 0.04)),
  };
}

// A daily-traffic-shaped series of completed windows plus an in-progress
// window, matching what a busy capture agent reports.
const windowShape = [1180, 1240, 1315, 1290, 1410, 1520, 1485, 1630, 1745, 1690, 1820, 1930, 2140, 2050, 1960];

export const mockStatsSnapshot: StatsSnapshot = {
  generatedAt: new Date().toISOString(),
  completedWindows: windowShape.map((requests, i) =>
    mockWindow(windowShape.length - i, requests)
  ),
  currentWindow: {
    ...mockWindow(0, 940),
    end: undefined,
  },
  uniqueClientIPs: 4287,
  uniqueFlows: 11902,
  topPaths: [
    { key: "/api/v1/orders", count: 9421 },
    { key: "/api/v1/products/search", count: 7256 },
    { key: "/api/v1/cart", count: 5110 },
    { key: "/api/v1/orders/{id}/status", count: 3874 },
    { key: "/healthz", count: 2930 },
    { key: "/api/v1/users/me", count: 2411 },
    { key: "/api/v1/checkout", count: 1980 },
  ],
  topClients: [
    { key: "10.0.14.7", count: 6112 },
    { key: "10.0.9.44", count: 4720 },
    { key: "10.2.3.18", count: 3391 },
    { key: "10.0.14.9", count: 2258 },
    { key: "10.1.7.203", count: 1904 },
  ],
  bodySizeBytes: {
    count: 292840,
    mean: 1490,
    p50: 618,
    p90: 4230,
    p99: 48100,
    max: 1048576,
  },
  handleLatencyMicros: {
    count: 292840,
    mean: 184,
    p50: 121,
    p90: 342,
    p99: 1180,
    max: 22400,
  },
  flowFilterFill: 0.078,
};
