//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentScalingSpec) DeepCopyInto(out *AgentScalingSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MaxReplicas != nil {
		in, out := &in.MaxReplicas, &out.MaxReplicas
		*out = new(int32)
		**out = **in
	}
	if in.TargetCPU != nil {
		in, out := &in.TargetCPU, &out.TargetCPU
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentScalingSpec.
func (in *AgentScalingSpec) DeepCopy() *AgentScalingSpec {
	if in == nil {
		return nil
	}
	out := new(AgentScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureAgentStatus) DeepCopyInto(out *CaptureAgentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureAgentStatus.
func (in *CaptureAgentStatus) DeepCopy() *CaptureAgentStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureAgentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureFilters) DeepCopyInto(out *CaptureFilters) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]HeaderMatch, len(*in))
		copy(*out, *in)
	}
	if in.PathPrefix != nil {
		in, out := &in.PathPrefix, &out.PathPrefix
		*out = new(string)
		**out = **in
	}
	if in.Percentage != nil {
		in, out := &in.Percentage, &out.Percentage
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureFilters.
func (in *CaptureFilters) DeepCopy() *CaptureFilters {
	if in == nil {
		return nil
	}
	out := new(CaptureFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHub) DeepCopyInto(out *CaptureHub) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHub.
func (in *CaptureHub) DeepCopy() *CaptureHub {
	if in == nil {
		return nil
	}
	out := new(CaptureHub)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureHub) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHubAuthentication) DeepCopyInto(out *CaptureHubAuthentication) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHubAuthentication.
func (in *CaptureHubAuthentication) DeepCopy() *CaptureHubAuthentication {
	if in == nil {
		return nil
	}
	out := new(CaptureHubAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHubCellStatus) DeepCopyInto(out *CaptureHubCellStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHubCellStatus.
func (in *CaptureHubCellStatus) DeepCopy() *CaptureHubCellStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureHubCellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHubList) DeepCopyInto(out *CaptureHubList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CaptureHub, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHubList.
func (in *CaptureHubList) DeepCopy() *CaptureHubList {
	if in == nil {
		return nil
	}
	out := new(CaptureHubList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureHubList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHubSpec) DeepCopyInto(out *CaptureHubSpec) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(CaptureHubTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Authentication != nil {
		in, out := &in.Authentication, &out.Authentication
		*out = new(CaptureHubAuthentication)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHubSpec.
func (in *CaptureHubSpec) DeepCopy() *CaptureHubSpec {
	if in == nil {
		return nil
	}
	out := new(CaptureHubSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHubSpokeStatus) DeepCopyInto(out *CaptureHubSpokeStatus) {
	*out = *in
	if in.LastHeartbeat != nil {
		in, out := &in.LastHeartbeat, &out.LastHeartbeat
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHubSpokeStatus.
func (in *CaptureHubSpokeStatus) DeepCopy() *CaptureHubSpokeStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureHubSpokeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHubStatus) DeepCopyInto(out *CaptureHubStatus) {
	*out = *in
	if in.Spokes != nil {
		in, out := &in.Spokes, &out.Spokes
		*out = make([]CaptureHubSpokeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]CaptureHubCellStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHubStatus.
func (in *CaptureHubStatus) DeepCopy() *CaptureHubStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureHubStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureHubTLSConfig) DeepCopyInto(out *CaptureHubTLSConfig) {
	*out = *in
	in.CertSecretRef.DeepCopyInto(&out.CertSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureHubTLSConfig.
func (in *CaptureHubTLSConfig) DeepCopy() *CaptureHubTLSConfig {
	if in == nil {
		return nil
	}
	out := new(CaptureHubTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureLoadTest) DeepCopyInto(out *CaptureLoadTest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureLoadTest.
func (in *CaptureLoadTest) DeepCopy() *CaptureLoadTest {
	if in == nil {
		return nil
	}
	out := new(CaptureLoadTest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureLoadTest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureLoadTestList) DeepCopyInto(out *CaptureLoadTestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CaptureLoadTest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureLoadTestList.
func (in *CaptureLoadTestList) DeepCopy() *CaptureLoadTestList {
	if in == nil {
		return nil
	}
	out := new(CaptureLoadTestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureLoadTestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureLoadTestSpec) DeepCopyInto(out *CaptureLoadTestSpec) {
	*out = *in
	out.SourceRef = in.SourceRef
	out.StorageRef = in.StorageRef
	in.Target.DeepCopyInto(&out.Target)
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(ReplayRateConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(ReplayFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = new(LoadTestDistribution)
		(*in).DeepCopyInto(*out)
	}
	if in.Abort != nil {
		in, out := &in.Abort, &out.Abort
		*out = new(LoadTestAbortPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Engine != nil {
		in, out := &in.Engine, &out.Engine
		*out = new(ReplayEngineSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureLoadTestSpec.
func (in *CaptureLoadTestSpec) DeepCopy() *CaptureLoadTestSpec {
	if in == nil {
		return nil
	}
	out := new(CaptureLoadTestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureLoadTestStatus) DeepCopyInto(out *CaptureLoadTestStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Assignments != nil {
		in, out := &in.Assignments, &out.Assignments
		*out = make([]LoadTestAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]LoadTestCellStatus, len(*in))
		copy(*out, *in)
	}
	if in.AchievedRPS != nil {
		in, out := &in.AchievedRPS, &out.AchievedRPS
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureLoadTestStatus.
func (in *CaptureLoadTestStatus) DeepCopy() *CaptureLoadTestStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureLoadTestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureSettings) DeepCopyInto(out *CaptureSettings) {
	*out = *in
	if in.IncludeHeaders != nil {
		in, out := &in.IncludeHeaders, &out.IncludeHeaders
		*out = new(bool)
		**out = **in
	}
	if in.IncludeBody != nil {
		in, out := &in.IncludeBody, &out.IncludeBody
		*out = new(bool)
		**out = **in
	}
	if in.MaxBodyBytes != nil {
		in, out := &in.MaxBodyBytes, &out.MaxBodyBytes
		*out = new(int64)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureSettings.
func (in *CaptureSettings) DeepCopy() *CaptureSettings {
	if in == nil {
		return nil
	}
	out := new(CaptureSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStorage) DeepCopyInto(out *CaptureStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStorage.
func (in *CaptureStorage) DeepCopy() *CaptureStorage {
	if in == nil {
		return nil
	}
	out := new(CaptureStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStorageList) DeepCopyInto(out *CaptureStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CaptureStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStorageList.
func (in *CaptureStorageList) DeepCopy() *CaptureStorageList {
	if in == nil {
		return nil
	}
	out := new(CaptureStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CaptureStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStorageReference) DeepCopyInto(out *CaptureStorageReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStorageReference.
func (in *CaptureStorageReference) DeepCopy() *CaptureStorageReference {
	if in == nil {
		return nil
	}
	out := new(CaptureStorageReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStorageSpec) DeepCopyInto(out *CaptureStorageSpec) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Config)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(GCSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EFS != nil {
		in, out := &in.EFS, &out.EFS
		*out = new(EFSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EBS != nil {
		in, out := &in.EBS, &out.EBS
		*out = new(EBSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(PluginConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(RetentionPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStorageSpec.
func (in *CaptureStorageSpec) DeepCopy() *CaptureStorageSpec {
	if in == nil {
		return nil
	}
	out := new(CaptureStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CaptureStorageStatus) DeepCopyInto(out *CaptureStorageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CaptureStorageStatus.
func (in *CaptureStorageStatus) DeepCopy() *CaptureStorageStatus {
	if in == nil {
		return nil
	}
	out := new(CaptureStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSConfig) DeepCopyInto(out *EBSConfig) {
	*out = *in
	if in.Filesystem != nil {
		in, out := &in.Filesystem, &out.Filesystem
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSConfig.
func (in *EBSConfig) DeepCopy() *EBSConfig {
	if in == nil {
		return nil
	}
	out := new(EBSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFSConfig) DeepCopyInto(out *EFSConfig) {
	*out = *in
	if in.Directory != nil {
		in, out := &in.Directory, &out.Directory
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFSConfig.
func (in *EFSConfig) DeepCopy() *EFSConfig {
	if in == nil {
		return nil
	}
	out := new(EFSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GCSConfig) DeepCopyInto(out *GCSConfig) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	in.CredentialsSecretRef.DeepCopyInto(&out.CredentialsSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GCSConfig.
func (in *GCSConfig) DeepCopy() *GCSConfig {
	if in == nil {
		return nil
	}
	out := new(GCSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderMatch) DeepCopyInto(out *HeaderMatch) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderMatch.
func (in *HeaderMatch) DeepCopy() *HeaderMatch {
	if in == nil {
		return nil
	}
	out := new(HeaderMatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestAbortPolicy) DeepCopyInto(out *LoadTestAbortPolicy) {
	*out = *in
	if in.MaxDuration != nil {
		in, out := &in.MaxDuration, &out.MaxDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ErrorPercent != nil {
		in, out := &in.ErrorPercent, &out.ErrorPercent
		*out = new(int32)
		**out = **in
	}
	if in.MinSampleRequests != nil {
		in, out := &in.MinSampleRequests, &out.MinSampleRequests
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestAbortPolicy.
func (in *LoadTestAbortPolicy) DeepCopy() *LoadTestAbortPolicy {
	if in == nil {
		return nil
	}
	out := new(LoadTestAbortPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestAssignment) DeepCopyInto(out *LoadTestAssignment) {
	*out = *in
	if in.ShardIndexes != nil {
		in, out := &in.ShardIndexes, &out.ShardIndexes
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestAssignment.
func (in *LoadTestAssignment) DeepCopy() *LoadTestAssignment {
	if in == nil {
		return nil
	}
	out := new(LoadTestAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestCellStatus) DeepCopyInto(out *LoadTestCellStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestCellStatus.
func (in *LoadTestCellStatus) DeepCopy() *LoadTestCellStatus {
	if in == nil {
		return nil
	}
	out := new(LoadTestCellStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestDistribution) DeepCopyInto(out *LoadTestDistribution) {
	*out = *in
	if in.Cells != nil {
		in, out := &in.Cells, &out.Cells
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxSpokes != nil {
		in, out := &in.MaxSpokes, &out.MaxSpokes
		*out = new(int32)
		**out = **in
	}
	if in.WorkersPerSpoke != nil {
		in, out := &in.WorkersPerSpoke, &out.WorkersPerSpoke
		*out = new(int32)
		**out = **in
	}
	if in.ConcurrencyPerWorker != nil {
		in, out := &in.ConcurrencyPerWorker, &out.ConcurrencyPerWorker
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestDistribution.
func (in *LoadTestDistribution) DeepCopy() *LoadTestDistribution {
	if in == nil {
		return nil
	}
	out := new(LoadTestDistribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadTestReference) DeepCopyInto(out *LoadTestReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadTestReference.
func (in *LoadTestReference) DeepCopy() *LoadTestReference {
	if in == nil {
		return nil
	}
	out := new(LoadTestReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PayloadPluginRef) DeepCopyInto(out *PayloadPluginRef) {
	*out = *in
	if in.OnError != nil {
		in, out := &in.OnError, &out.OnError
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PayloadPluginRef.
func (in *PayloadPluginRef) DeepCopy() *PayloadPluginRef {
	if in == nil {
		return nil
	}
	out := new(PayloadPluginRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginConfig) DeepCopyInto(out *PluginConfig) {
	*out = *in
	if in.Symbol != nil {
		in, out := &in.Symbol, &out.Symbol
		*out = new(string)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginConfig.
func (in *PluginConfig) DeepCopy() *PluginConfig {
	if in == nil {
		return nil
	}
	out := new(PluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayEngineSpec) DeepCopyInto(out *ReplayEngineSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayEngineSpec.
func (in *ReplayEngineSpec) DeepCopy() *ReplayEngineSpec {
	if in == nil {
		return nil
	}
	out := new(ReplayEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayFilters) DeepCopyInto(out *ReplayFilters) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.PathPrefix != nil {
		in, out := &in.PathPrefix, &out.PathPrefix
		*out = new(string)
		**out = **in
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayFilters.
func (in *ReplayFilters) DeepCopy() *ReplayFilters {
	if in == nil {
		return nil
	}
	out := new(ReplayFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayRateConfig) DeepCopyInto(out *ReplayRateConfig) {
	*out = *in
	if in.RequestsPerSecond != nil {
		in, out := &in.RequestsPerSecond, &out.RequestsPerSecond
		*out = new(int32)
		**out = **in
	}
	if in.TimeScale != nil {
		in, out := &in.TimeScale, &out.TimeScale
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayRateConfig.
func (in *ReplayRateConfig) DeepCopy() *ReplayRateConfig {
	if in == nil {
		return nil
	}
	out := new(ReplayRateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayShardSpec) DeepCopyInto(out *ReplayShardSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayShardSpec.
func (in *ReplayShardSpec) DeepCopy() *ReplayShardSpec {
	if in == nil {
		return nil
	}
	out := new(ReplayShardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayTarget) DeepCopyInto(out *ReplayTarget) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayTarget.
func (in *ReplayTarget) DeepCopy() *ReplayTarget {
	if in == nil {
		return nil
	}
	out := new(ReplayTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplayTransformRef) DeepCopyInto(out *ReplayTransformRef) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplayTransformRef.
func (in *ReplayTransformRef) DeepCopy() *ReplayTransformRef {
	if in == nil {
		return nil
	}
	out := new(ReplayTransformRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetentionPolicy) DeepCopyInto(out *RetentionPolicy) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(string)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetentionPolicy.
func (in *RetentionPolicy) DeepCopy() *RetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(RetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Config) DeepCopyInto(out *S3Config) {
	*out = *in
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	in.CredentialsSecretRef.DeepCopyInto(&out.CredentialsSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Config.
func (in *S3Config) DeepCopy() *S3Config {
	if in == nil {
		return nil
	}
	out := new(S3Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficCapture) DeepCopyInto(out *TrafficCapture) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficCapture.
func (in *TrafficCapture) DeepCopy() *TrafficCapture {
	if in == nil {
		return nil
	}
	out := new(TrafficCapture)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficCapture) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficCaptureList) DeepCopyInto(out *TrafficCaptureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficCapture, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficCaptureList.
func (in *TrafficCaptureList) DeepCopy() *TrafficCaptureList {
	if in == nil {
		return nil
	}
	out := new(TrafficCaptureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficCaptureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficCaptureReference) DeepCopyInto(out *TrafficCaptureReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficCaptureReference.
func (in *TrafficCaptureReference) DeepCopy() *TrafficCaptureReference {
	if in == nil {
		return nil
	}
	out := new(TrafficCaptureReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficCaptureSpec) DeepCopyInto(out *TrafficCaptureSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.StorageRef = in.StorageRef
	in.Capture.DeepCopyInto(&out.Capture)
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(CaptureFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.Agent != nil {
		in, out := &in.Agent, &out.Agent
		*out = new(AgentScalingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Plugins != nil {
		in, out := &in.Plugins, &out.Plugins
		*out = make([]PayloadPluginRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficCaptureSpec.
func (in *TrafficCaptureSpec) DeepCopy() *TrafficCaptureSpec {
	if in == nil {
		return nil
	}
	out := new(TrafficCaptureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficCaptureStatus) DeepCopyInto(out *TrafficCaptureStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.BytesWritten != nil {
		in, out := &in.BytesWritten, &out.BytesWritten
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.AgentStatus != nil {
		in, out := &in.AgentStatus, &out.AgentStatus
		*out = new(CaptureAgentStatus)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficCaptureStatus.
func (in *TrafficCaptureStatus) DeepCopy() *TrafficCaptureStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficCaptureStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficReplay) DeepCopyInto(out *TrafficReplay) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficReplay.
func (in *TrafficReplay) DeepCopy() *TrafficReplay {
	if in == nil {
		return nil
	}
	out := new(TrafficReplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficReplay) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficReplayList) DeepCopyInto(out *TrafficReplayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TrafficReplay, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficReplayList.
func (in *TrafficReplayList) DeepCopy() *TrafficReplayList {
	if in == nil {
		return nil
	}
	out := new(TrafficReplayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrafficReplayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficReplaySpec) DeepCopyInto(out *TrafficReplaySpec) {
	*out = *in
	out.SourceRef = in.SourceRef
	out.StorageRef = in.StorageRef
	in.Target.DeepCopyInto(&out.Target)
	if in.Rate != nil {
		in, out := &in.Rate, &out.Rate
		*out = new(ReplayRateConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(ReplayFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.Transforms != nil {
		in, out := &in.Transforms, &out.Transforms
		*out = make([]ReplayTransformRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.Shard != nil {
		in, out := &in.Shard, &out.Shard
		*out = new(ReplayShardSpec)
		**out = **in
	}
	if in.LoadTestRef != nil {
		in, out := &in.LoadTestRef, &out.LoadTestRef
		*out = new(LoadTestReference)
		**out = **in
	}
	if in.Engine != nil {
		in, out := &in.Engine, &out.Engine
		*out = new(ReplayEngineSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficReplaySpec.
func (in *TrafficReplaySpec) DeepCopy() *TrafficReplaySpec {
	if in == nil {
		return nil
	}
	out := new(TrafficReplaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficReplayStatus) DeepCopyInto(out *TrafficReplayStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.MeanLatency != nil {
		in, out := &in.MeanLatency, &out.MeanLatency
		*out = new(string)
		**out = **in
	}
	if in.P50Latency != nil {
		in, out := &in.P50Latency, &out.P50Latency
		*out = new(string)
		**out = **in
	}
	if in.P95Latency != nil {
		in, out := &in.P95Latency, &out.P95Latency
		*out = new(string)
		**out = **in
	}
	if in.P99Latency != nil {
		in, out := &in.P99Latency, &out.P99Latency
		*out = new(string)
		**out = **in
	}
	if in.AchievedRPS != nil {
		in, out := &in.AchievedRPS, &out.AchievedRPS
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficReplayStatus.
func (in *TrafficReplayStatus) DeepCopy() *TrafficReplayStatus {
	if in == nil {
		return nil
	}
	out := new(TrafficReplayStatus)
	in.DeepCopyInto(out)
	return out
}
