{{- if and .Values.history.enabled .Values.history.localPostgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kapture.history.localPostgres.name" . }}
  namespace: {{ include "kapture.namespace" . }}
  labels:
    {{- include "kapture.history.localPostgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.history.localPostgres.auth.database | quote }}
  POSTGRES_USER: {{ .Values.history.localPostgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.history.localPostgres.auth.password | quote }}
{{- end }}
