{{- if and .Values.hub.enabled .Values.hub.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kapture.hub.serviceAccountName" . }}
  namespace: {{ include "kapture.namespace" . }}
  labels:
    {{- include "kapture.hub.labels" . | nindent 4 }}
  {{- with .Values.hub.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

