{{- if and .Values.hub.enabled .Values.hub.serviceAccount.create }}
{{- $annotations := dict -}}
{{- with .Values.hub.serviceAccount.annotations }}
{{- $annotations = merge $annotations . -}}
{{- end }}
{{- if and .Values.hub.irsa.enabled .Values.hub.irsa.roleArn }}
{{- $annotations = merge $annotations (dict "eks.amazonaws.com/role-arn" .Values.hub.irsa.roleArn) -}}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kapture.hub.serviceAccountName" . }}
  namespace: {{ include "kapture.namespace" . }}
  labels:
    {{- include "kapture.hub.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
