{{- if .Values.hub.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kapture.fullname" . }}-hub
  namespace: {{ include "kapture.namespace" . }}
  labels:
    {{- include "kapture.hub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: {{ .Values.hub.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.hub.service.dashboardPort }}
      targetPort: dashboard
      protocol: TCP
      name: dashboard
  selector:
    {{- include "kapture.hub.selectorLabels" . | nindent 4 }}
{{- end }}
